### ISSUE TITLE
.spt support SystemNNN

### ISSUE THREAD

**Issue by eliasstein** [arcusmaximus/VNTranslationTools#1]
Can you add a support for .spt files from the system nnn engine? at the moment only exist a tool called gsspt but only works with short novels made in that engine in long novels for example sadistic blood this tool doesnt work

i know that the game use a xor encryption with the key FF in all the bytes but i stuck there i don't know how to continue so if you can add support to that files i really appreciate it. oh and the source code of systemnnn is here on github, thanks.

**Comment by xenei** [comment]
Hey I can't seem to Able to compile it, and I am kind of dire need for this tool. If you had already compiled successfully, Can you please send me it? I'll be really thankful to you, thanks.

**Comment by arcusmaximus** [comment]
.spt support implemented.
