### ISSUE TITLE
About encrypted .ybn

### ISSUE THREAD

**Issue by KTOhz** [arcusmaximus/VNTranslationTools#10]
Hello. I want to ask, is it possible to edit encrypted .ybn files through VNTextPatch? Just, I found out that the files are encrypted with some key, but I don't know what kind of key and where to get it. I need help. Thanks in advance.

**Comment by Cosetto** [comment]
> Hello. I want to ask, is it possible to edit encrypted .ybn files through VNTextPatch? Just, I found out that the files are encrypted with some key, but I don't know what kind of key and where to get it. I need help. Thanks in advance.

Use GARbro and try using **"Try to guess"** to extract ypf folder. GARbro will auto guess the key and decrypt for you. After that use VNtextpatch to extract all .ybn files with "extractlocal" and insert back with "insertlocal"

**Comment by arcusmaximus** [comment]
VNTextPatch automatically circumvents the default .ybn encryption. If your specific game uses additional archive-level encryption, it's indeed up to an archive extraction tool like GARbro to decrypt that.
