### ISSUE TITLE
Yu-Ris character names showing up in textbox

### ISSUE THREAD

**Issue by PoisonPyte** [arcusmaximus/VNTranslationTools#101]
VN: https://vndb.org/v31434

Using VnTextPatch to extract and insert the scripts, the names of characters show up in the textbox instead of above it. The scripts extracted to the excel file are missing the Japanese 「」quotations which I think are required for the game engine to recognize a line as a spoken dialogue. Also, it seems when inserted into the .ybn files, all 「」quotations are replaced with ‘’. 
I've had success with editing the script and having the names show up properly when using [OzmafiaScriptThing.7z](https://web.archive.org/web/20140208002246/http://tlwiki.org/images/0/02/OzmafiaScriptThing.7z) (source code included). 

I've included example scripts inserted by VnTextPatch and OzmafiaScriptThing. Note, the file "yst00071.ybn" contains the name lists of characters. 
[Yu-Ris.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10342557/Yu-Ris.zip)

![vntextpatch](https://user-images.githubusercontent.com/99261186/210515368-cfd46376-75ad-4865-9a30-fb4ca3bba865.JPG)

**Comment by Cosetto** [comment]
Read [this](https://github.com/arcusmaximus/VNTranslationTools/issues/31#issuecomment-1099534133) and use version [v0.0.15](https://github.com/arcusmaximus/VNTranslationTools/releases/tag/v0.0.15). For now, newer versions than 0.0.15 will result in the names show up in textbox

**Comment by arcusmaximus** [comment]
These ‘...’ quotes were for a translation project I was involved in myself (where we customized the game to use those quotes instead of 「」). Shouldn't have been committed. They're reverted to 「」 now.
