### ISSUE TITLE
Questions about txt.scn repacking in kirikiri engine

### ISSUE THREAD

**Issue by Refrain69** [arcusmaximus/VNTranslationTools#102]
When I repack .json into .scn files,a "box" occurs at the end of the line.
![屏幕截图 2023-01-04 172058](https://user-images.githubusercontent.com/121091208/210524464-e10034f2-c74c-43eb-bd8a-7673efc98725.png)
this is the original text.
![屏幕截图 2023-01-04 172158](https://user-images.githubusercontent.com/121091208/210524565-70703572-40fb-435b-ae00-f942c88b159f.png)
this is what happened after repacking.
However,the "box" disappeared in another font.
![屏幕截图 2023-01-04 173309](https://user-images.githubusercontent.com/121091208/210525237-6fe9c1bc-5b60-430d-88c2-7c0d1e8abc8a.png)
How to deal with that?Any helps are appreciated.

**Comment by Cosetto** [comment]
Same problem with [this](https://github.com/arcusmaximus/VNTranslationTools/issues/61#issuecomment-1182010865). To fix it, go to open vntextpatch.exe.config with any text editor and config the word-wrap value, **key="MonospaceCharactersPerLine" value="50"**. For Chinese, I think you don't need to wrap the text, so just make the value **1000**

**Comment by Refrain69** [comment]
Thanks for your help,but still not work……
![屏幕截图 2023-01-04 202318](https://user-images.githubusercontent.com/121091208/210554624-578f97f8-ec49-41f1-b645-c1dcd955b90a.png)
![屏幕截图 2023-01-04 202449](https://user-images.githubusercontent.com/121091208/210554636-d4cc28d8-bddd-4e91-b931-6f0dbbc802ef.png)
By the way,what's the meaning of"don't need to wrap the text"?Maybe just use json files rather than repack into scn?sorry i'm a fool:-(

**Comment by Cosetto** [comment]
Weird, that guy said it worked. Try using [this](https://github.com/marcussacana/KrKrZSceneManager), open the scn file and scroll that line to see what character is it

**Comment by arcusmaximus** [comment]
If you can compile VNTextPatch yourself, please try making the following change in PsbScript.cs on line 65:

```cs
psb.Text.Value = ProportionalWordWrapper.Default.Wrap(StringUtil.FancifyQuotes(str.Text, @"\$.+?;"), null, "\\n");
```

If that fixes the problem, let me know so I can apply the change.

If you can't compile VNTextPatch, please attach a sample translation and let me know which font causes the box to appear.

**Comment by Refrain69** [comment]
the txt.scn file:
[s01-1_a.txt.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10344372/s01-1_a.txt.zip)
the font file:   
[simhei.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10344388/simhei.zip)
Thanks very much!

**Comment by Refrain69** [comment]
The line is here  id=215
![屏幕截图 2023-01-04 223141](https://user-images.githubusercontent.com/121091208/210577591-1d4551ab-c20e-4ffa-ba13-99af84c575fb.png)
真奈美一边抑制着声音的颤抖，一边结束了在脑海中思考已久的自我介绍。

the font name is 黑体

**Comment by arcusmaximus** [comment]
I didn't want to spend too much time figuring out which of the 10 different configuration files changes the font, so I just went ahead and made the change. Please test the new build.

**Comment by Refrain69** [comment]
Both the VNTranslationTools and KirikiriUnencryptedArchive work perfectly now.Thank you very much!
