### ISSUE TITLE
Kirikiri .ks file extraction problem (UTF-16 vs. SHIFT-JIS)

### ISSUE THREAD

**Issue by Tooko1005** [arcusmaximus/VNTranslationTools#107]
For [CharaBration!](https://vndb.org/v23242), when I try to extract the .ks files into an excel document, I only get garbled question marks as shown here:
![01-07-2023_14-01-09](https://user-images.githubusercontent.com/102438293/211171937-ae579c65-855b-4c2a-ab10-4fd02b8d76ec.jpg)
But when I open the same .ks files in Notepad++, it renders correctly, but only in the UTF-16 Little Endian encoding, as shown here: 
![01-07-2023_13-59-25](https://user-images.githubusercontent.com/102438293/211172021-08964afc-dd59-4469-b107-51d0e5bae974.jpg)
At least from what I can tell, VNTranslationTools is extracting the .ks files using the SHIFT-JIS encoding, which produces the error. Is there a way to tell the program to extract using UTF-16 Little Endian?
[Charabration script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10367281/Charabration.script.zip)

**Comment by Refrain69** [comment]
Save the files in "UTF-16 LE with bom",then extract.

**Comment by Cosetto** [comment]
Would recommend you to use krkrextract to extract again
![image](https://user-images.githubusercontent.com/81801486/211178270-a1ce72e1-2569-4ecd-9652-05bbe543d920.png)

**Comment by Tooko1005** [comment]
Thanks @Cosetto. The problem was that Garbro hadn't extracted them correctly, and it worked after using Krkrextract.
