### ISSUE TITLE
(YU-RIS) Inserting translation or original Japanese text back breaks the game.

### ISSUE THREAD

**Issue by Sai-key** [arcusmaximus/VNTranslationTools#109]
Hi! I'm using version 0.0.30 of VNTextPatch.

Translated a few lines of a yu-ris game and it completely brakes the game when inserting the translation back.
So I tried just extracting the text from the .ybn files and then inserting back the excel sheet without touching anything (leaving the original text intact) and the game brakes anyway.
When I say it breaks the game I mean it starts behaving weirdly by showing the same few lines over and over and even skipping some events. Tried messing around with the .config linewidths but it was no use.

[Original_ybn_files.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10397465/Original_ybn_files.zip)

**Comment by arcusmaximus** [comment]
Re-extracting the patched files seems to work at least. Please let me know which game this is for so I can test.

**Comment by Sai-key** [comment]
> Re-extracting the patched files seems to work at least. Please let me know which game this is for so I can test.

https://www.dlsite.com/maniax/work/=/product_id/RJ197770.html

You can start the game, but you will inmediately see the glitches after the first text is shown.

**Comment by arcusmaximus** [comment]
Fixed.
