### ISSUE TITLE
"Too many lines in translated script" error

### ISSUE THREAD

**Issue by bregassa** [arcusmaximus/VNTranslationTools#11]
Hi..
I get "Too many lines in translated script" error during insertlocal command after I'm done translating script.xlsx
What's wrong and what should I do?

**Comment by bregassa** [comment]
sometimes I also get ""Not enough lines in translated script" error
Can someone tell me what this errors mean and what should I do to fix them?

**Comment by arcusmaximus** [comment]
It means your .xlsx file contains either more or less lines (or character names) than are in the original scenario file.

**Comment by bregassa** [comment]
> It means your .xlsx file contains either more or less lines (or character names) than are in the original scenario file.

Hi.. so I actually found the real culprit.. we can't translate "／" to "/".. I replace all the "/" back to "／" then everything back to normal

**Comment by arcusmaximus** [comment]
Right - VNTextPatch treats half-width slashes in character names as a separator. This is to handle cases where one line has two names attached: a real one and a displayed one (e.g. "Kirino/???"). If you replace a full-width slash in a name by a half-width one, VNTextPatch will think there are now two names and raise an error.

If needed, you can change this separator in ExcelScript.cs.

**Comment by kokoiro** [comment]
@arcusmaximus I'm getting this error even though I edited one (1) line. (YU-RIS engine)

**Comment by arcusmaximus** [comment]
@kokoiro Please create a new ticket and attach the scripts of the game where you get the error.
