### ISSUE TITLE
Artemis Engine issue

### ISSUE THREAD

**Issue by RedEye13** [arcusmaximus/VNTranslationTools#116]
Hey I found a code structure that VNTextPatch can't parse I'll upload the script of the 2 games I have but basically all Artemis games made by [Pachipachi Soft](https://vndb.org/p4248) are the same 
![image](https://user-images.githubusercontent.com/30023402/216057648-bbf31d62-3f54-4cef-9d8a-45aa5c517826.png)

[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10557470/script.zip)
[script2.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10557477/script2.zip)

**Comment by RedEye13** [comment]
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10560040/script.zip)
Well I did think it was because those games had a different struct than the ones that work fine but this one has the same struct and it's also throwing the invalid token exception 

I'm not sure if this helps in any way but I just thought I should mention it

**Comment by arcusmaximus** [comment]
Should all work now.
