### ISSUE TITLE
Found invalid data while decoding (YU-RIS )

### ISSUE THREAD

**Issue by Sai-key** [arcusmaximus/VNTranslationTools#119]
Hi!

While extracting a folder of .ybn files I get the error "Found invalid data while decoding" on some of them.
The only way to continue the extraction is to delete those files which of course is not ideal if they contain relevant in-game text.
The list of files failing are:
yst0110 - yst00112 - yst00113 - yst00114 - yst00122 - yst00137
![image](https://user-images.githubusercontent.com/116866187/218918553-c061d29d-46bd-4b7a-9f60-494d4499be38.png)

[input.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10738983/input.zip)
The VN: https://www.dlsite.com/maniax/work/=/product_id/RJ269227.html

Thanks in advance ^^

**Comment by arcusmaximus** [comment]
I took a look, but it seems these files really are invalid (missing data). Going by their small sizes, chances are they're not important for translation either.
