### ISSUE TITLE
Index out of array bounds（Csystem）

### ISSUE THREAD

**Issue by blw1234** [arcusmaximus/VNTranslationTools#120]
It seems that the text should be exported well, but even if I put it back intact, it will prompt that the index exceeds the array limit.
This is a game [https://vndb.org/v13730](url)
In addition, does this engine not support SJIS tunnel?
[input.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10743698/input.zip) 
![image](https://user-images.githubusercontent.com/120999489/219047921-aae55573-37b7-4358-97af-34cafe6edbde.png)

**Comment by Cosetto** [comment]
Yes, it does support sjistunnel

**Comment by arcusmaximus** [comment]
Crashes in both VNTextPatch and VNTextProxy for this game should be fixed now. I also added a new proxy for msacm32.dll, which you can use here without requiring Setdll.

**Comment by Cosetto** [comment]
Tested on another [Heiantei's game](https://vndb.org/v21645). Lmao, idk what is the shadow thing
![image](https://user-images.githubusercontent.com/81801486/219538222-7ad524e0-e25d-4ec4-bfb7-86b8d9460b00.png)

**Comment by blw1234** [comment]
The crash problem of this game has been well solved
But I also encountered the above shadow problem, and this is also the case in my translated text
![image](https://user-images.githubusercontent.com/120999489/219575259-f6609273-21d8-4c6f-8c14-9e1e45ac7062.png)

**Comment by arcusmaximus** [comment]
Doesn't seem to occur with the original Japanese. Can you send an archive file with a translation that triggers it?

**Comment by Cosetto** [comment]
> The crash problem of this game has been well solved But I also encountered the above shadow problem, and this is also the case in my translated text ![image](https://user-images.githubusercontent.com/120999489/219575259-f6609273-21d8-4c6f-8c14-9e1e45ac7062.png)

Try to shrink the font in the config dSy.dat

**Comment by blw1234** [comment]
It seems that I didn't put Chinese fonts in the game root directory. Sorry

**Comment by arcusmaximus** [comment]
Please try this version, then - it has the character repositioning disabled since you won't need it anyway for Chinese.
[msacm32.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10776488/msacm32.zip)

**Comment by blw1234** [comment]
The black shadow has disappeared. There are no other problems except that the mapped font is a little small. Thank you very much for your help
![image](https://user-images.githubusercontent.com/120999489/220135495-77ef689f-8e3d-40bc-ac69-6f0e32b63a3a.png)
