### ISSUE TITLE
Softpal / POINT.DAT / Found invalid data while decoding

### ISSUE THREAD

**Issue by gozu4456** [arcusmaximus/VNTranslationTools#122]
Receiving this error message from cmd, "POINT.DAT Found invalid data while decoding. ". I suppose this is because something is different. Could you look at it and perhaps offer some solutions? 
For information, the game is: [DLsite](https://www.dlsite.com/pro/work/=/product_id/VJ006446.html/?unique_op=af&locale=en_US)
Also, here is the script files, in case you need to study them
[scriptfiles.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10774275/scriptfiles.zip)

**Comment by Cosetto** [comment]
Read [this](https://github.com/arcusmaximus/VNTranslationTools/issues/82#issuecomment-1296133566)

**Comment by Cosetto** [comment]
The command should be
Extract:
**vntextpatch.exe extractlocal input/script.src script.xlsx**
or
vntextpatch.exe extractlocal input/script.src script/script.json**

Insert:
**vntextpatch.exe insertlocal input/script.src script.xlsx output/script.src**
or
**vntextpatch.exe insertlocal input/script.src script/script.json output/script.src**

Output file only has script.src and text.dat

**Comment by gozu4456** [comment]
Thanks, that information helped me. However, I did a text check: it's working; Did a choice check: it's not there in the script. 
The choice Text should be above the [blue selected text] as shown in the next picture, which is from another dumper tool only for extracting. 
![image](https://user-images.githubusercontent.com/125741672/219878793-7fdf67ec-86ab-4761-99c1-c4cb7eaf3bf5.png)
![image](https://user-images.githubusercontent.com/125741672/219878954-157ea597-f24c-4d46-a960-dfaac519c813.png)
the main Vntextpatch tool doesn't seem to have extracted them. Any solutions?

**Comment by Cosetto** [comment]
Seems like missing opcode or something
![image](https://user-images.githubusercontent.com/81801486/219932254-40c4e508-3ade-4d48-b4bf-b11d2513a742.png)

**Comment by arcusmaximus** [comment]
Looks like this game uses a custom function for displaying choices, rather than the engine's built-in one. This is not something VNTextPatch can detect, so a generic solution isn't possible. Instead, I made a quick customization for this specific game.
[VNTextPatch.Shared.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10776525/VNTextPatch.Shared.zip)

**Comment by gozu4456** [comment]
I see, thanks. The patch .dll seemed to have worked and successfully extract the remaining choices. Did all check and everything is OK, again, thanks and highly appreciate the effort.
