### ISSUE TITLE
question on wrapping kirikiri script

### ISSUE THREAD

**Issue by shiny-ribbon** [arcusmaximus/VNTranslationTools#124]
how can I disable the fancify quotes function? 
the reason is that with the font I'm using, it adds an unreasonable amount of width to apostrophes. 
before and after:

![31969](https://user-images.githubusercontent.com/35888744/221423197-80734920-17e6-4d23-8238-5552e2801429.jpg)
![31971](https://user-images.githubusercontent.com/35888744/221423203-7d4fe38a-4193-4154-9b9d-badb19ee340e.jpg)

I tried downloading the source code, but the build.bat didn't build anything for me, and of course I'm not entirely sure what part of the code would need disabling. so basically, can I disable the quote / apostrophe replacing, and how can I compile after doing so. 
Thank you and sorry for the beginner question

**Comment by arcusmaximus** [comment]
Simply edit this line:
https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Kirikiri/KirikiriScnScript.cs#L65
to this:
```cs
psb.Text.Value = ProportionalWordWrapper.Default.Wrap(str.Text, ControlCodeRegex, "\\n");
```

You can then open VNTranslationTools.sln in Visual Studio (there's a free Community edition) and press F5 to build it.

**Comment by shiny-ribbon** [comment]
Thank you for the help. 
Unfortunately even after installing VS, I couldn't rebuild it myself. I ran into a bunch of errors and the program is way too complicated for me. Oh well, I tried

**Comment by Cosetto** [comment]
I bet you forgot to download external/Freemote
