### ISSUE TITLE
Some scn files cannot be parsed(一些scn文件无法解析)

### ISSUE THREAD

**Issue by wycstc353** [arcusmaximus/VNTranslationTools#125]
[krkr.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10920503/krkr.zip)
発情スイッチ ～美姉妹が催眠術に堕ちた先～
网盘链接：https://pan.baidu.com/s/19_4yqoNPd_3KaA2U7VUpOw
提取码：liox

秒传：
eaf084b17260ce39ba3068c050fbfda1#1289105138#hatsujosw.rar

解压码：混沌心海

**Comment by Cosetto** [comment]
English please

**Comment by wycstc353** [comment]
> English please

Thank you, but I've got the answer elsewhere
