### ISSUE TITLE
About encoding

### ISSUE THREAD

**Issue by xd2333** [arcusmaximus/VNTranslationTools#128]
Thanks for making these tools.What's the encoding when insert?Can I specify the encoding?

**Comment by Cosetto** [comment]
Depend on the engine but mostly shift-jis, you can't change encoding of game's script because the game won't work if you change it

**Comment by xd2333** [comment]
Since generally in us this is done by modifying the game program to make the text display properly with modifyed encodeing, I would like to ask how to modify the inserted encoding. I'm not very good at C#, can you provide  a basic idea about how to add this feature so I can try to change it myself?thanks

**Comment by Cosetto** [comment]
There's no need, vntextpatch has a function called sjistunnelencoding which will output ext_sjis.bin when you insert the text has chracters which is not supported by shift-jis. Place ext_ext.bin, a proxy(.dll which the game prefers), and a .ttf/.otf font to support your language in the game folder, it will help displaying non-supporting characters in the game.

**Comment by xd2333** [comment]
hi, I'v tryed vntextproxy in the catsystem2 game アマカノ2 ～Perfect Edition～ with version.dll, but the game crash at the begaining before windows show.can you fix it or how can i debug it?thanks
