### ISSUE TITLE
SjisTunnelEncoding

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#129]
I'm not sure if this is possible or not, but can we make the SjisTunnelEncoding function turned non-sjis characters into a single byte character instead of two bytes? This is because most of the engines have problem like this "Thí s is a té sting sé ntence." as you see.

**Comment by arcusmaximus** [comment]
That won't work, no. The whole idea behind tunnel encoding is not to replace any existing characters, and the only way to achieve that in SJIS is to use two bytes. To fix the double width ingame, you then have to patch the engine.

If you don't mind replacing existing characters to get down to one byte, you can take a look at this related project: https://github.com/AtomCrafty/UniversalInjectorFramework
