### ISSUE TITLE
Blurred text beyond the text container

### ISSUE THREAD

**Issue by bregassa** [arcusmaximus/VNTranslationTools#13]
I notice there's this Clockup VN that will blur overflow text outside of it text container.
Do you have any tips on how to fix this?

![Untitled](https://user-images.githubusercontent.com/22976574/147587399-553d2719-c6ac-417b-802d-7f29b5822819.png)

It also will blur overflow text in choice text

**Comment by Cosetto** [comment]
> I notice there's this Clockup VN that will blur overflow text outside of it text container. Do you have any tips on how to fix this?
> 
> ![Untitled](https://user-images.githubusercontent.com/22976574/147587399-553d2719-c6ac-417b-802d-7f29b5822819.png)
> 
> It also will blur overflow text in choice text

Check issue #5

**Comment by bregassa** [comment]
> > I notice there's this Clockup VN that will blur overflow text outside of it text container. Do you have any tips on how to fix this?
> > ![Untitled](https://user-images.githubusercontent.com/22976574/147587399-553d2719-c6ac-417b-802d-7f29b5822819.png)
> > It also will blur overflow text in choice text
> 
> Check issue #5

That issue talking about weird gaps between line break.. what I have problem with is the black blurred overflow text in my screenshot

**Comment by arcusmaximus** [comment]
Just like the gaps after line breaks, this blurring issue is likely due to a problem in the game's text rendering scripts. Fixing it would require decompiling, editing and recompiling the scripts, and I'm not aware of any YU-RIS decompiler.

In short: I don't have any tips on how to fix this, and it's likely not a problem in VNTextPatch in the first place (meaning this Github project is not the right place to ask about it). Sorry.

**Comment by Cosetto** [comment]
> > > I notice there's this Clockup VN that will blur overflow text outside of it text container. Do you have any tips on how to fix this?
> > > ![Untitled](https://user-images.githubusercontent.com/22976574/147587399-553d2719-c6ac-417b-802d-7f29b5822819.png)
> > > It also will blur overflow text in choice text
> > 
> > 
> > Check issue #5
> 
> That issue talking about weird gaps between line break.. what I have problem with is the black blurred overflow text in my screenshot

You can actually fix it by doing the same thing like MangGamer did with their Clock up's vn. 
![image](https://user-images.githubusercontent.com/81801486/147668233-9f352ddb-1107-449a-8804-902db0fc818f.png)
.png font is the solution to it. I don't know how to custom it. 
![image](https://user-images.githubusercontent.com/81801486/147668782-97dd6ac1-7b61-46fb-bde6-87be31140f46.png)
[yst00011.zip](https://github.com/arcusmaximus/VNTranslationTools/files/7789114/yst00011.zip)
This is the font file from Euphoria(ENG)
