### ISSUE TITLE
Question: How does the program use Columns, can I add columns?

### ISSUE THREAD

**Issue by Kayot** [arcusmaximus/VNTranslationTools#132]
Does the program use the columns in the order that they appear, or does it use the header?

I want to add another column to the sheets for google translations. I plan to use those to crutch myself during translations since I would be like an N7 if that existed. IE, I can read a bit of Japanese, but I wouldn't want to get lost in Japan.

Would adding a column mess the refeed up?

**Comment by arcusmaximus** [comment]
The columns that VNTextPatch reads are fixed. You can add extra columns to the right, however (they'll simply be ignored).

That being said, if you're referring to N7 as in JLPT N7 - two levels below the lowest - you may want to reconsider getting into translation so soon. That time would be better spent studying.
