### ISSUE TITLE
.spt tool doesn't recognize command for changeable name

### ISSUE THREAD

**Issue by KuronekoRM** [arcusmaximus/VNTranslationTools#19]
In the game Clover Toshokan no Juunintachi you can choose a name for the protagonist, so in the script the name appears as #名 but in-game it's supposed to show the name the player wrote in the name input screen.
However, when I reinsert the text, the name of the protagonist simply shows as #名 instead of the chosen name. Also, it's probably not recognised as a name, since it doesn't show in a different textbox as it actually should.

**Comment by arcusmaximus** [comment]
This behavior is intentional, as (at least in my experience so far), translations are more likely to use `#` as a text character than a SystemNNN escape sequence. If you want to change this, you can remove the responsible line of code in SystemNnnBaseScript.FormatFileText().
