### ISSUE TITLE
Yu-RIS Word-Wrap Tool?

### ISSUE THREAD

**Issue by xenei** [arcusmaximus/VNTranslationTools#2]
Hello maximus,
I've been working on a Yu-RIS engine title since forever.. I recently found out about your tool for Yu-RIS engine, but I don't any issue with getting the text or re-inserting them back. I however have a issue with Word-wrapping for Yu-RIS engine, It only accepts " manual spcaes " such as - 

![space](https://user-images.githubusercontent.com/91423244/141119630-9ca01eea-041f-4bbb-bb02-0bc8f7a3cb32.PNG)
result in-game -
![this](https://user-images.githubusercontent.com/91423244/141119693-1df8eb7e-0d05-41a4-abde-f0adaf3ef59a.PNG)

And for a normal person without any proper background on coding I don't have any work-around without doing them manually which in the long run will probably exhaust me.
So I am here kindly requesting you, if you can make a work-around or tool that can add spaces and fix Yu-RIS word-wrapping problem. The VN I am working is this  - https://vndb.org/v23179 

Thank you, and best regards,
xenei

**Comment by arcusmaximus** [comment]
It looks like I disabled wordwrapping for YU-RIS and forgot to enable it again before putting the tool on Github. I re-enabled it now. Please rebuild the tool and, in VNTextPatch.exe.config, change the setting "MonospaceCharactersPerLine" to the number of characters per line in your game. You should then get fully automatic wordwrapping without having to add spaces yourself.
