### ISSUE TITLE
Specified cast is not valid.

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#21]
I was testing with this [one](https://vndb.org/v470) of Ai6win and that line pop up. Here's the script
[mes.zip](https://github.com/arcusmaximus/VNTranslationTools/files/7958436/mes.zip)

**Comment by arcusmaximus** [comment]
Fixed. Closing with mandatory image for machine translation:

![image](https://user-images.githubusercontent.com/133129/152636540-b91b1b30-469e-48f3-b529-3bd4f3265465.png)
