### ISSUE TITLE
Lists don't have equal number of items

### ISSUE THREAD

**Issue by bregassa** [arcusmaximus/VNTranslationTools#22]
I get this kind of error in some VNs when patching script
"Lists don't have equal number of items"
I wonder what's the reason of this error? and how to fix this?
below is the script.

[Lists don't have equal number of items (Script Example).zip](https://github.com/arcusmaximus/VNTranslationTools/files/8001342/Lists.don.t.have.equal.number.of.items.Script.Example.zip)

**Comment by arcusmaximus** [comment]
Fixed. Closing with mandatory image for machine translation:

![image](https://user-images.githubusercontent.com/133129/152636898-b885dd89-5805-48f4-b658-08a6ebd40ba2.png)
