### ISSUE TITLE
Unable to extract the script for newer BGI games

### ISSUE THREAD

**Issue by PoisonPyte** [arcusmaximus/VNTranslationTools#23]
I'm having trouble extracting the script files for 放課後シンデレラ and Pure x Connect - Full HD Remaster. "The given key was not present in the dictionary"

I've attached the ._bp files and two script files for 放課後シンデレラ.
[放課後シンデレラ.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8023938/default.zip)

**Comment by arcusmaximus** [comment]
Fixed for 放課後シンデレラ. Let me know if it works for Pure x Connect too now.

**Comment by PoisonPyte** [comment]
Thanks, it worked for both game. A couple more issues I found:
1. I noticed the choice selection text were not being picked up. 放課後シンデレラ has all the choices (Ex: Talk to her/Don't talk to her) contained in the script files as text. 
2. I am unable to use "&" in the names.xml for character names. It gives me an error on the line that has & in it. No issues if I change it to "and" instead. (Sometimes two characters are speaking at the same time like "Kiyoshirou & Youka")

**Comment by AtomCrafty** [comment]
`&` is a reserved character in XML files, so you need to escape it like this: `&amp;`. [Here](https://dev.w3.org/html5/html-author/charref) is a list of all entity sequences.

**Comment by PoisonPyte** [comment]
@AtomCrafty Thanks!

**Comment by arcusmaximus** [comment]
Turns out 放課後シンデレラ doesn't use Ethornell's built-in choice screen but has its own custom function. VNTextPatch now recognizes it.
