### ISSUE TITLE
Missing key for Silky's engine

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#24]
[Script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8140925/Script.zip)
Game: https://vndb.org/v28884

**Comment by arcusmaximus** [comment]
Fixed. You know the drill...
![image](https://user-images.githubusercontent.com/133129/158014693-670b6a9f-ee11-46c9-9619-9cbaa9b79372.png)
