### ISSUE TITLE
VNTextProxy, How can I use Custom font in kirikiri game?

### ISSUE THREAD

**Issue by Ninelie-Nananai** [arcusmaximus/VNTranslationTools#27]
Hello, [arcusmaximus](https://github.com/arcusmaximus)

I'm trying to translate [Moto Yankee Tsuma Hinako](https://vndb.org/v30294) to Thai language.

I'm using [VNTextPatch](https://github.com/arcusmaximus/VNTranslationTools) to translate and wondering how to use VNTextProxy

After I translated some text into Thai and put the file in the game folder to test and this happened

<img src="https://i.ibb.co/JH5d4L5/Screenshot-2022-03-27-053838.png"/>

I wondering how can I add a custom font [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) in to the game?

**Comment by Cosetto** [comment]
> Hello, [arcusmaximus](https://github.com/arcusmaximus)
> 
> I'm trying to translate [Moto Yankee Tsuma Hinako](https://vndb.org/v30294) to Thai language.
> 
> I'm using [VNTextPatch](https://github.com/arcusmaximus/VNTranslationTools) to translate and wondering how to use VNTextProxy
> 
> After I translated some text into Thai and put the file in the game folder to test and this happened
> 
> ![](https://camo.githubusercontent.com/5f6b9ab2556768df0397383e6f1e22261e1f2cedae8448fddc2dd11a238e776e/68747470733a2f2f692e6962622e636f2f4a483564344c352f53637265656e73686f742d323032322d30332d32372d3035333833382e706e67)
> 
> I wondering how can I add a custom font [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) in to the game?

You can change the font name in Config.tjs, backlog's font should be in there too. It should be Userface if I'm not wrong, after changing put Config.tjs in the patch too

**Comment by Ninelie-Nananai** [comment]
<img src="https://i.ibb.co/FDmdzRB/Screenshot-2022-03-28-102412.png"/>

I changed the Userface but nothing happened The game still uses built-in fonts or game engine font (not sure).
Can I import my [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) font and set it to a variable or something else?

**Comment by Ninelie-Nananai** [comment]
> > Hello, [arcusmaximus](https://github.com/arcusmaximus)
> > I'm trying to translate [Moto Yankee Tsuma Hinako](https://vndb.org/v30294) to Thai language.
> > I'm using [VNTextPatch](https://github.com/arcusmaximus/VNTranslationTools) to translate and wondering how to use VNTextProxy
> > After I translated some text into Thai and put the file in the game folder to test and this happened
> > ![](https://camo.githubusercontent.com/5f6b9ab2556768df0397383e6f1e22261e1f2cedae8448fddc2dd11a238e776e/68747470733a2f2f692e6962622e636f2f4a483564344c352f53637265656e73686f742d323032322d30332d32372d3035333833382e706e67)
> > I wondering how can I add a custom font [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) in to the game?
> 
> You can change the font name in Config.tjs, backlog's font should be in there too. It should be Userface if I'm not wrong, after changing put Config.tjs in the patch too

<img src="https://i.ibb.co/FDmdzRB/Screenshot-2022-03-28-102412.png"/>

I changed the Userface but nothing happened The game still uses built-in fonts or game engine font (not sure).
Can I import my [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) font and set it to a variable or something else?

**Comment by Cosetto** [comment]
> > > Hello, [arcusmaximus](https://github.com/arcusmaximus)
> > > I'm trying to translate [Moto Yankee Tsuma Hinako](https://vndb.org/v30294) to Thai language.
> > > I'm using [VNTextPatch](https://github.com/arcusmaximus/VNTranslationTools) to translate and wondering how to use VNTextProxy
> > > After I translated some text into Thai and put the file in the game folder to test and this happened
> > > ![](https://camo.githubusercontent.com/5f6b9ab2556768df0397383e6f1e22261e1f2cedae8448fddc2dd11a238e776e/68747470733a2f2f692e6962622e636f2f4a483564344c352f53637265656e73686f742d323032322d30332d32372d3035333833382e706e67)
> > > I wondering how can I add a custom font [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) in to the game?
> > 
> > 
> > You can change the font name in Config.tjs, backlog's font should be in there too. It should be Userface if I'm not wrong, after changing put Config.tjs in the patch too
> 
> ![](https://camo.githubusercontent.com/eeb578d523c18d2e368a0904413faa579252bd2bd888eea52cee8815846384f5/68747470733a2f2f692e6962622e636f2f46446d647a52422f53637265656e73686f742d323032322d30332d32382d3130323431322e706e67)
> 
> I changed the Userface but nothing happened The game still uses built-in fonts or game engine font (not sure). Can I import my [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) font and set it to a variable or something else?

The should be a place to change font in menu bar, try it

**Comment by Ninelie-Nananai** [comment]
<img src="https://i.ibb.co/CKhQgkx/Screenshot-2022-03-28-104038.png"/>

I see only default fonts

**Comment by Ninelie-Nananai** [comment]
> > > > Hello, [arcusmaximus](https://github.com/arcusmaximus)
> > > > I'm trying to translate [Moto Yankee Tsuma Hinako](https://vndb.org/v30294) to Thai language.
> > > > I'm using [VNTextPatch](https://github.com/arcusmaximus/VNTranslationTools) to translate and wondering how to use VNTextProxy
> > > > After I translated some text into Thai and put the file in the game folder to test and this happened
> > > > ![](https://camo.githubusercontent.com/5f6b9ab2556768df0397383e6f1e22261e1f2cedae8448fddc2dd11a238e776e/68747470733a2f2f692e6962622e636f2f4a483564344c352f53637265656e73686f742d323032322d30332d32372d3035333833382e706e67)
> > > > I wondering how can I add a custom font [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) in to the game?
> > > 
> > > 
> > > You can change the font name in Config.tjs, backlog's font should be in there too. It should be Userface if I'm not wrong, after changing put Config.tjs in the patch too
> > 
> > 
> > ![](https://camo.githubusercontent.com/eeb578d523c18d2e368a0904413faa579252bd2bd888eea52cee8815846384f5/68747470733a2f2f692e6962622e636f2f46446d647a52422f53637265656e73686f742d323032322d30332d32382d3130323431322e706e67)
> > I changed the Userface but nothing happened The game still uses built-in fonts or game engine font (not sure). Can I import my [Cordia New](https://docs.microsoft.com/th-th/typography/font-list/cordia-new) font and set it to a variable or something else?
> 
> The should be a place to change font in menu bar, try it

<img src="https://i.ibb.co/CKhQgkx/Screenshot-2022-03-28-104038.png"/>

I see only default fonts

Maybe I can't just changed the Userface.

**Comment by Cosetto** [comment]
I think you need to custom the font in order to make the game accepts it base on MS Gothic font, you will need to add glyphs for Thai's letters or wait for arc_ to help you with the proxy. If you want this is a font you can use
[Genshin.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8359574/Genshin.zip)
You need an app like FontForge to custom, add glyphs and outline for Thai's letters

**Comment by Ninelie-Nananai** [comment]
> I think you need to custom the font in order to make the game accepts it base on MS Gothic font, you will need to add glyphs for Thai's letters or wait for arc_ to help you with the proxy. If you want this is a font you can use [Genshin.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8359574/Genshin.zip) You need an app like FontForge to custom, add glyphs and outline for Thai's letters

<img src="https://i.ibb.co/h28xGHg/Screenshot-2022-03-28-135406.png"/>

Hey, [Cosetto](https://github.com/Cosetto) I think, I'm on the right way

I added thai alphabet to [Malgun Gothic](https://docs.microsoft.com/th-th/typography/font-list/malgun-gothic) by using [FontForge](https://fontforge.org/en-US/)

The font looks weird, but I think I can fix it myself.

### Thank you very much [Cosetto](https://github.com/Cosetto) for your information. It helped me a lot!

**Comment by arcusmaximus** [comment]
Inside VNTextProxy, you can change the font over here:
https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextProxy/Proportionalizer.cpp#L9

(Just change the line to `FontName = L"Cordia New";`)
That way, you don't need to create a custom font file.
