### ISSUE TITLE
Missing code during insertlocal for BGI/Ethornell

### ISSUE THREAD

**Issue by Tooko1005** [arcusmaximus/VNTranslationTools#28]
I am having an issue with encoding during insertlocal. I do not have this issue when I try to encode the files with BGIKit's ScriptEncoder, but I'm still trying to figure out what I'm doing wrong here. I first used extractlocal to spit out the script.xlsx file, then ran it again after editing the names in names.xml, then I ran insertlocal with that script.xlsx using the syntax VNTextPatch insertlocal \orig script.xlsx \patch where C:\Orig contains one of the original script files, ev0010.bgi. The command works in that it spits out ev0010.bgi into C:\Patch, but when I open it in EthernelEditor, there are some commands missing.

Below shows the original file (left) and the encoded file from insertlocal (right) in EthornellEditor. Scene and BGM commands disappear during the encoding process, and the IS_ECG102_s01 command gets duplicated at the beginning, replacing _FadeBGM. The game files are from [Ima Sugu Onii-chan ni Imouto da tte Iitai!](https://vndb.org/v7766).
![03-26-2022_15-29-18](https://user-images.githubusercontent.com/102438293/160259350-46483448-b85f-42a5-b3a1-c52a5efd0a14.jpg)

**Comment by arcusmaximus** [comment]
The above code change should fix it.

**Comment by Tooko1005** [comment]
It did fix it, thank you.
