### ISSUE TITLE
Gap after line-breaks of YU-RIS engine

### ISSUE THREAD

**Issue by xenei** [arcusmaximus/VNTranslationTools#3]
Hello maximus,
Your Yu-RIS Word-Wrapping tool has been working for me flawlessly for the last vn that I had shown you, but I also found out with your tool I can also work with my favorite Vns - [Clock Up](https://vndb.org/p200) titles - however I am having a slight issue with it, it has some weird two-character spaces after every link-break - this is what I am talking about ――

![gap](https://user-images.githubusercontent.com/91423244/141812985-3e9dd19f-16cd-49b8-9ec7-4e113545d003.PNG)
Here's some better examples ――

![Capture](https://user-images.githubusercontent.com/91423244/141815417-04fcb148-5932-46ab-820f-82baf736d995.PNG)

![sd](https://user-images.githubusercontent.com/91423244/141813760-48fc459e-3d00-4baf-a658-4270ad7e779f.PNG)

![gap2](https://user-images.githubusercontent.com/91423244/141813751-ea0f5c21-0a35-4b99-83f3-7f356bd561f9.PNG)

 I tried both Monospace and Proportional but nothing seems to work or maybe I am doing something wrong.  I hope to you if you have any solution to this or maybe something needs to be changed like the fonts etc. This is the VN I encountered this issue - https://vndb.org/v18806 , Once Again thanks for this amazing tool!

Thank you and best regards,
xenei

**Comment by xenei** [comment]
One thing I forgot to add, my apologies for that; is It looks completely normal while reading in backlog. So I guess this is either font issue or something else.... ―
![Capture](https://user-images.githubusercontent.com/91423244/142719244-e08ba808-a1d1-457a-baeb-4b5a4c536ca9.PNG)

**Comment by arcusmaximus** [comment]
In YU-RIS games, each character is individually rendered and positioned by the .ybn scripts, not by the engine itself. And while YU-RIS comes with a set of default scripts for rendering text blocks that (mostly) work fine with half-width characters, I'm guessing this particular company customized the code and messed something up.

Fixing this would require decompiling, fixing and recompiling the scripts. While VNTextProxy can fix bad character positioning in some engines, YU-RIS isn't one of those.

So, I'm sorry, but there's not much I can do about this.
