### ISSUE TITLE
Specified method is not supported

### ISSUE THREAD

**Issue by LxxAA** [arcusmaximus/VNTranslationTools#31]
[ysbin.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8461451/ysbin.zip)
the name of the game is リンカーベル・アカデミア 落第魔女とヒミツの儀式 (removed the ～)
there are two problems,first is the ??? (name) should be on top of the text not on the same row,the second is the ? at the end,some random lines have a ? at the end 
![image](https://user-images.githubusercontent.com/103406907/162676510-65748572-974b-4e41-a686-df3e1a90f0ba.png)

(p.s. human translation)

**Comment by arcusmaximus** [comment]
YU-RIS games have a name list script that also needs to be translated (yst00069 in this game). Once you fill it in, the text should show up correctly.

![image](https://user-images.githubusercontent.com/133129/163457833-ba0ce875-d745-4ef6-a090-25bf730142ba.png)

I did make one code change after looking at the scripts of this game, which is to add support for dialogue that uses『』or（）instead of「」.

> (p.s. human translation)

Finally someone who's doing it right :)

**Comment by LxxAA** [comment]
![unknown](https://user-images.githubusercontent.com/103406907/163513363-a3a441a5-4674-49c9-88f6-d0285d3afee5.png)

**Comment by arcusmaximus** [comment]
Works for me... You're using the current version of the source code, right? Could you debug and see where exactly the exception is coming from?

**Comment by Ming-2015** [comment]
> 

![image](https://user-images.githubusercontent.com/25674083/163657922-a7ff7d1d-bdb0-4ba2-bbfe-ead765814c4e.png)

Was asked to help with getting the debug callstack to work.  The exception callstack is as follows:
`>	VNTextPatch.Shared.dll!VNTextPatch.Shared.Util.SjisTunnelEncoding.GetCharCount(byte[] bytes, int index, int count) Line 119	C#
 	mscorlib.dll!System.Text.Encoding.GetChars(byte[] bytes, int index, int count)	Unknown
 	mscorlib.dll!System.Text.Encoding.GetString(byte[] bytes, int index, int count)	Unknown
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Scripts.Yuris.YurisScript.EvaluatePushStringExpression(VNTextPatch.Shared.Scripts.Yuris.YurisAttribute attr) Line 317	C#
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Scripts.Yuris.YurisScript.GetAttributeValue(VNTextPatch.Shared.Scripts.Yuris.YurisAttribute attr) Line 291	C#
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Scripts.Yuris.YurisScript.GetStringAttributes(VNTextPatch.Shared.Scripts.Yuris.YurisCommand command, System.Collections.Generic.List<VNTextPatch.Shared.Scripts.Yuris.YurisAttribute> attrs) Line 248	C#
 	mscorlib.dll!System.Collections.Generic.List<VNTextPatch.Shared.Scripts.Yuris.YurisAttribute>.InsertRange(int index, System.Collections.Generic.IEnumerable<VNTextPatch.Shared.Scripts.Yuris.YurisAttribute> collection)	Unknown
 	mscorlib.dll!System.Collections.Generic.List<VNTextPatch.Shared.Scripts.Yuris.YurisAttribute>.AddRange(System.Collections.Generic.IEnumerable<VNTextPatch.Shared.Scripts.Yuris.YurisAttribute> collection)	Unknown
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Scripts.Yuris.YurisScript.GetStringAttributeGroups() Line 209	C#
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Scripts.Yuris.YurisScript.GetStrings() Line 88	C#
 	mscorlib.dll!System.Collections.Generic.List<VNTextPatch.Shared.ScriptString>.List(System.Collections.Generic.IEnumerable<VNTextPatch.Shared.ScriptString> collection)	Unknown
 	System.Core.dll!System.Linq.Enumerable.ToList<VNTextPatch.Shared.ScriptString>(System.Collections.Generic.IEnumerable<VNTextPatch.Shared.ScriptString> source)	Unknown
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Extracter.ExtractOne(string inputScriptName, string textScriptName) Line 43	C#
 	VNTextPatch.Shared.dll!VNTextPatch.Shared.Extracter.ExtractAll() Line 71	C#
 	VNTextPatch.exe!VNTextPatch.Program.ExtractLocal(string[] args, VNTextPatch.Program.Options options) Line 77	C#
 	VNTextPatch.exe!VNTextPatch.Program.Main(string[] args) Line 30	C#
`

**Comment by arcusmaximus** [comment]
Should be fixed now.
