### ISSUE TITLE
Resquest: .MAP of Silky engine

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#33]
New version of Silky engine I guess, scrips are not in .MES anymore only code there, real scripts are in .MAP in data.arc
.Map is used in [this](https://vndb.org/v27457) and steam version of [Doukyuusei-Remake](https://vndb.org/v34136)
This is the script of Doukyuusei-Remake. I only need to get the English script out for translation.
[Silky.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8495557/Silky.zip)

**Comment by Cerzs** [comment]
It's also used in Kimaten.

Btw, sorry for asking in your issue, but do you have this compiled? (With all fontproxy dll) I couldn't compile it myself. Ty.

**Comment by Cosetto** [comment]
the d2d1 doesn't work for every games, you have to change the font name in the proxy and compile it again in like arc_  [said](https://github.com/arcusmaximus/VNTranslationTools/issues/27#issuecomment-1080324975)
[vntextpatch.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8500830/vntextpatch.zip)

**Comment by Berthog** [comment]
Also interested in this because Kimiten.

**Comment by arcusmaximus** [comment]
Support added. Note that these .map files only contain the message text, not the character names.
