### ISSUE TITLE
.MAP files Unexpected message index error. 

### ISSUE THREAD

**Issue by Berthog** [arcusmaximus/VNTranslationTools#34]
Hello, thanks for the new update for the Silk's .map format. I tried to use it but got unexpected message index error in the process after decompile a few scripts. I tried first just with the english scripts of https://vndb.org/v26000 and then with japanese, english and chinese all together (from the english release).  
[scripts.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8507193/scripts.zip)

**Comment by arcusmaximus** [comment]
Looks like the number of the last message inside the file is sometimes 0... I removed the check.
