### ISSUE TITLE
Translation file has too many lines error

### ISSUE THREAD

**Issue by Berthog** [arcusmaximus/VNTranslationTools#35]
Sorry for the second issue post in the same day, but I got this error in a game that I'm translating atm. Engine is Kirikiri Z core and the file format is .ks. I tried reading old issues and I know that error would appears because too many characters (as the message error says) and by changing some things like " / " to "/". I checked my xlsx and there's not that kind of errors (I also tried to limit the characters writen) but the process still stops always in the third script, script that, needed to say, I haven't worked in at all. Could you take a look on it please? This is the game just in case: https://vndb.org/v28644
and I'm also attaching my xlsx and original scripts. 
[scenario.xlsx](https://github.com/arcusmaximus/VNTranslationTools/files/8509166/scenario.xlsx)
[scenario.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8509171/scenario.zip)
PD: Program still resambled the first two scripts, I repacked them and works perfectly (just some wordwrap errors, but I think that's because the difference between the characters in the line translated and the original).

**Comment by Berthog** [comment]
Also I think there's a problem in the wordwrap for this game. The configurations are setted in 50 characters per line by default, but that wordwrap doesn't work and the line cut in the character 71 or so. I don't know if this have relation with the tool or it's just maybe the game but just in case, I point it too. 
![image](https://user-images.githubusercontent.com/84604636/163915220-8f9d888c-76d2-468d-8263-b65a61120cc3.png)

**Comment by Cosetto** [comment]
**_ProportionalLineWidth" value="1000"_** is the wrap for kirikiri,

**Comment by Berthog** [comment]
> **_ProportionalLineWidth" value="1000"_** is the wrap for kirikiri, in your case just decrease to 900 or smaller.

The wordwrap works perfectly now, thank you very much Cosetto.

**Comment by arcusmaximus** [comment]
Should be fixed - please re-extract and try again.

**Comment by Berthog** [comment]
> Should be fixed - please re-extract and try again.

Tested and it's repacking all scripts normally now. Thank you very much.

**Comment by Berthog** [comment]
I'm reoping this issue for just a little issue. Extracting and repacking works perfectly with this game now, but in my most recent test, I found 2 errors, I don't know is it's directly related with the tool, but I'll say it just in case. The first error was in the replacement of some original - translated lines. I think it's just in this kind of games that has a system to choose a "nickname" for the main character or let you write your name instead. The lines in the scripts extracted will looks like this
![image](https://user-images.githubusercontent.com/84604636/164103031-1a1f82e8-a164-41cb-899d-ab552ae0e977.png)
If you write your translation in the TL line, when you repack the script and then the patch, this replacement or change will not shows in the game, althought you can force it just replacing the original line. I haven't tried to do the same process with other tools tho so I'm not sure if it just happen in this one.
The second problem is a message error that close the game abrutly.
![image](https://user-images.githubusercontent.com/84604636/164103829-30f6fc88-e539-4f7b-892d-bc810eed8d5d.png)

**Comment by Cosetto** [comment]
>

> I'm reopening this issue for just a some little problems. Extracting and repacking works perfectly with this game now, but in my most recent test, I found 2 errors, I don't know if it's directly related with the tool, but I'll let you know just in case. The first error was in the replacement of some original - translated lines. I think it's just in this kind of games that has a system that allow you to choose a "nickname" for the main character or let you write your name instead. The lines in the scripts extracted will looks like this ![image](https://user-images.githubusercontent.com/84604636/164103031-1a1f82e8-a164-41cb-899d-ab552ae0e977.png) If you write your translation in the TL line, when you repack the script and then make the patch, this replacement or change will not shows in the game, althought you can force it just translating in the original line. I haven't tried to do the same process with other tools tho so I'm not sure if this happen just in this tool. The second problem is a message error that close the game abruptly. This only happens if you click on backlog's option. ![image](https://user-images.githubusercontent.com/84604636/164103829-30f6fc88-e539-4f7b-892d-bc810eed8d5d.png)

Try to put scripts back to scenarios folder in data.xp3 not patch.xp3 for the backlog. For the name thing I think they're in .tjs in system folder?

**Comment by Berthog** [comment]
> Try to put scripts back to scenarios folder in data.xp3 not patch.xp3 for the backlog. For the name thing I think they're in .tjs in system folder?

Yes, no problem with the names at the moment, names are in the file "nicknames.tjs" and I managed to fix that. I'll try to pack the scenarios in data.xp3 to test again the backlog thing. Thank you very much. 


> For the split lines, try adding the nickname command to `AllowedInlineCommands` in KirikiriScript.cs. (As mentioned in the README of this repository, Kirikiri typically requires some game-specific customization)
> 
Understood, thank you for your assistance.
