### ISSUE TITLE
The given key was not present in the dictionary.(BGI)

### ISSUE THREAD

**Issue by Sisulizer** [arcusmaximus/VNTranslationTools#36]
I'm trying to port the old English version of [Desire](https://vndb.org/v151) to remake version using BGI, but some scripts can't be extracted. I've also included the ._bp files if you need them
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8511781/script.zip)

**Comment by arcusmaximus** [comment]
Missing opcodes added - should work now.

**Comment by Sisulizer** [comment]
Thanks
