### ISSUE TITLE
HorkEye Engine help

### ISSUE THREAD

**Issue by SanLukaku** [arcusmaximus/VNTranslationTools#37]
Hello, sorry for inconvenience, I wonder if is possible add support for HorkEye Engine's scripts. I tried to  extract arc.dat of one game but I don't know the file extension of the scripts, and there's not really many tools that support this engine (and some one them are quite complicated to understand for me) I'm attaching one script here just in case, also the game is this one, it's for a translation project. Thank you in adavance https://vndb.org/v22880
[00001D3587EF8E0F46D43.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8526918/00001D3587EF8E0F46D43.zip)

**Comment by SanLukaku** [comment]
Addtional info, it seems it's the same engine that uses the games of Minato soft of the lastest years. It's some kind of improved whale engine(? or something like that, I don't really know.

**Comment by Cosetto** [comment]
Send the whole scripts, not only that file, and you will need a filename.lst to indicate the name of the script when unpacking. You can try to pull request for [this one](https://github.com/vn-tools/whale-tools), I think the owner is still active. Also this engine need some kind of harsh key or something, [this one](https://github.com/crskycode/GalgameCoding/tree/main/NonColor/Tools) is the second tool I found for it(need key to unpack/repack), since it's full of Chinese so I translate the buttons with deepl
[Noncolor.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8527191/Noncolor.zip)

**Comment by SanLukaku** [comment]
[Uploading shukusai_scripts.zip…]()

**Comment by Cosetto** [comment]
![image](https://user-images.githubusercontent.com/81801486/164480639-06fbdc6f-d3b3-4e5a-a3a1-80e35ac89939.png)
Actually a friend of mine ported the artemis version of that game to window(need original version), if you need I can send the convert batch to you to use

**Comment by arcusmaximus** [comment]
Support added. I didn't test it ingame, so please try it out and let me know if it works.

**Comment by Arata12** [comment]
Sorry for asking here, but someone know how to repack the files into .dat for this engine?

**Comment by Cosetto** [comment]
> Send the whole scripts, not only that file, and you will need a filename.lst to indicate the name of the script when unpacking. You can try to make issue for [this one](https://github.com/vn-tools/whale-tools), I think the owner is still active. Also this engine need some kind of harsh key or something, [this one](https://github.com/crskycode/GalgameCoding/tree/main/NonColor/Tools) is the second tool I found for it(need key to unpack/repack), since it's full of Chinese so I translate the buttons with deepl [Noncolor.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8527191/Noncolor.zip)

@Arata12 need Name title and harsh key to unpack/repack

**Comment by Berthog** [comment]
If I'm not wrong, harsh key for this one is x9d0be0fa and title is just 宿星のガールフレンド. I've tried the only working tool available but it didn't worked not even changing this parameters, idk if I'm doing it wrong, but at least that was what I got from my test. Would be very useful if someone know a way to repack the scripts into .dat again.
