### ISSUE TITLE
Error with CaféStella scripts (.scn)

### ISSUE THREAD

**Issue by Arata12** [arcusmaximus/VNTranslationTools#38]
Hello, I'm translating [café stella to shinigami no chou](https://vndb.org/v26414) to my language and I tried to use yours tool because are nicer for translating, but I got some errors.  First one is that the tool try to process the .ks.scn files but gets 0 lines and process stop, no .xlsx is created. Then I tried to compile and decompile the scn with another tool and this time the scripts were procesed but with this result. I don't really know the origin of this, would you please check it? Here's some scripts.

[scripts.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8527121/scripts.zip)
Also for scripts with multiple languages, is there a way to extract text for only one language like english for example?
![image](https://user-images.githubusercontent.com/34563333/164369413-9ea95a4d-be06-4016-aa11-e0e4f35292a0.png)

**Comment by Cosetto** [comment]
How can you even make that works for Café Stella steam version? I thought the steam version use some kind of **M2** crypt? Even version.dll doesn't work

**Comment by Arata12** [comment]
> How can you even make that works for Café Stella steam version? I thought the steam version use some kind of **M2** crypt? Even version.dll doesn't work

Actually, you can make it work with version.dll but is very limited to only translate scripts since you need to replace the original scn.xp3 file, but since is very limited we are working with something else

I didn't do it myself, so I only know the theory, basically you make a .dll with this one the mod tells the game to load the file you modified from an unencrypted .xp3, for this you need to make a table it has de index and (optional) hash of the original file, for this you need to enable the debug mode.

Something like this:
![image](https://user-images.githubusercontent.com/34563333/164386967-b96fa15e-8c6e-4816-9545-092953b1b797.png)

proof:
![image](https://user-images.githubusercontent.com/34563333/164387554-d1b580a0-f53d-483d-93bc-564a40135548.png)

**Comment by Cosetto** [comment]
I see.  Are you any chance working with Jast version or steam version? I can't dump anything from steam version because the .exe got packed with something.

**Comment by Arata12** [comment]
jast version to dump files, but patch should work for both versions

**Comment by Arata12** [comment]
If you want to ask more, feel free to contact me on Discord: Arata12#8538

**Comment by arcusmaximus** [comment]
This game uses a slightly different .scn structure than the games I've seen previously. VNTextPatch now supports both.

>  is there a way to extract text for only one language like english for example?
If you want to extract a different language than Japanese, you can open PsbScript.cs, look for `multiLanguageTexts[0]`. and change the 0 to a 1.

**Comment by Arata12** [comment]
tested, it´s working, thanks :pray: 
![image](https://user-images.githubusercontent.com/34563333/164539965-f3654d66-cb1a-49a2-8bd9-66f2f3dfcc06.png)

**Comment by Arata12** [comment]
It seems choices are still in Japanese when I change multiLanguageTexts[0] to multiLanguageTexts[1]. 
![image](https://user-images.githubusercontent.com/34563333/164948712-9bb5b284-e6d5-4384-8892-69f738988822.png)

**Comment by arcusmaximus** [comment]
PsbScript.cs now has a constant called `LanguageIndex` at the top that controls both dialogue and choices. As before, change it to 1 to get English instead of Japanese.

**Comment by Arata12** [comment]
It seems working for me
![image](https://user-images.githubusercontent.com/34563333/165031985-44446a4c-8aeb-40c6-9452-acbdf011b2db.png)
