### ISSUE TITLE
Add support musica engine (*.sc)

### ISSUE THREAD

**Issue by imKota** [arcusmaximus/VNTranslationTools#4]
Can you add a support for .sc files from the musica engine?

**Comment by arcusmaximus** [comment]
Basic support implemented (no wordwrapping). Do you happen to know if the engine has a control code for manual line breaks?

**Comment by imKota** [comment]
Hello, @arcusmaximus 


> Do you happen to know if the engine has a control code for manual line breaks?

manual line breaks `\n`

**Comment by arcusmaximus** [comment]
Thanks, added it.

**Comment by imKota** [comment]
@arcusmaximus about scripts.

Some games have choices. There are often two of them, but there may be more.

`.select Kiss　her:label1 Don't　kiss　her:label2`

`.select {text}:label1 {text2}:label2`
`.select {text}:label1 {text2}:label2 {text3}:label3`


![image](https://user-images.githubusercontent.com/24241471/145276776-81ec6158-a865-472a-9f51-cb198386aa8b.png)
![image](https://user-images.githubusercontent.com/24241471/145276944-47c86718-dc58-4edc-8178-0a82b45234bb.png)

**Comment by arcusmaximus** [comment]
Of course, how could I forget heh. Added.

**Comment by imKota** [comment]
@arcusmaximus thanks :33
