### ISSUE TITLE
Error with Qlie .s files

### ISSUE THREAD

**Issue by Berthog** [arcusmaximus/VNTranslationTools#40]
Hello, I was testing the tool with a game based on Qlie (.s) and got this problem, it doesn't extract text but weirdo characters. It looks like this happens because the original codification of the text in the game, that is shift-JIS.
Tested with: [Biman 3](https://vndb.org/v14365)
![image](https://user-images.githubusercontent.com/84604636/164750242-f6d58702-45da-49e8-9abb-9a26ead02bfd.png)
Scripts for reference: 
[scenario.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8542353/scenario.zip)

**Comment by Berthog** [comment]
As additional note, tool works if you change from shift-jis to utf16, but this (in this game at least) will do the game to crash.

**Comment by arcusmaximus** [comment]
I guess different versions of the engine use different encodings... VNTextPatch now detects the encoding and uses the appropriate one.
