### ISSUE TITLE
About alternate proxies

### ISSUE THREAD

**Issue by Arata12** [arcusmaximus/VNTranslationTools#41]
Do I need to modify something besides the files from "AlternateProxies"? Since I get an error because [this line](https://github.com/arcusmaximus/VNTranslationTools/blob/21bc263d8b69dec314b510dc3d2cd1305209a725/VNTextProxy/D2DProportionalizer.cpp#L57)

Btw, I get the same error when I try to compile as "release" even with the original files (d2d1)

log:
[VNTextProxy.log](https://github.com/arcusmaximus/VNTranslationTools/files/8546301/VNTextProxy.log)

**Comment by arcusmaximus** [comment]
Until now, D2DProportionalizer.cpp required the D2D1 proxy to be active, meaning that if you used a different proxy, you had to remove the D2DProportionalizer from the project. I changed the code so this is no longer necessary.
