### ISSUE TITLE
Add support for JSON

### ISSUE THREAD

**Issue by dreamsavior** [arcusmaximus/VNTranslationTools#42]
Thank you for the great tools.
This is not an issue, but a feature request.
Is it possible to add support for JSON format? I mean, dumping the translatable texts into the excel spreadsheet is great and all. But dumping the scripts into JSON files will allow the translators to work it through automation easily to their desired CAT tools. Not to mention the elimination of the dependency to Microsoft products.

**Comment by arcusmaximus** [comment]
The tool already supported .txt files, but apparently I forgot to document that (and well, you'd have to write a custom parser to split the names from the messages and handle newlines and stuff, so they weren't as convenient as .json anyway).

The .txt file support is now replaced by .json, and the documentation now actually mentions that it's available.

**Comment by Cosetto** [comment]
![image](https://user-images.githubusercontent.com/81801486/166434728-89f8082f-9a9e-4e0f-b87e-a100f48df678.png)
Do I need to specify something like --format=json?

**Comment by arcusmaximus** [comment]
No - I just missed one file while committing.
