### ISSUE TITLE
Issues with VNTextProxy

### ISSUE THREAD

**Issue by Arata12** [arcusmaximus/VNTranslationTools#43]
1. It's not working with [Golden Marriage](https://vndb.org/v14264).
2. SJIS tunneling is not working with [Shukusei no Girlfriend](https://vndb.org/v22880).

For Golden Marriage I already checked the .exe, and there is reference to d3d9, also tried using locale emu function, but I didn't worked, so I don't know if this engine is incompatible or is just my game or something else. (AdvHD)

For Shukusei i also used d3d9,dll and it worked for font, but It didn't worked SJIS tunneling. (Whale Engine)
![image](https://user-images.githubusercontent.com/34563333/165244585-82ebb171-08a7-4921-86d9-cd3044d8532c.png)
[sjis_ext.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8560795/sjis_ext.zip) 
By the way, this is just a question, I tried using VNProxy with Doukyuusei English Version, but It seems this version It uses Images to display chars, so I was wondering if you know a possible solution or maybe someone else.

**Comment by Arata12** [comment]
I wanted to ask more about this, I wanted to make a proxy for dsound, but when i already did it, the game crashed, i tried with 2 different games, well the thing is, I saw [this](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextProxy/pch.h#L11), so I wanted to ask is that the reason my proxy is not working or is something else? 

Also, for proxies, if i want to make one I need to add every function or i can only add the ones my game uses? asking this because d3d9.dll
[DSound.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8569889/DSound.zip)

**Comment by arcusmaximus** [comment]
Let's go one game at a time. The above commit should make tunneling work for Shukusei no Girlfriend - could you try it out? If it still doesn't work, could you send me an adjusted script archive + sjis_ext.bin?

> I wanted to ask more about this, I wanted to make a proxy for dsound, but when i already did it, the game crashed

Win32AToWAdapter.cpp also works with DirectSound, so if you create a proxy, it needs to be made aware of that (similar to the `#ifdef VNTEXTPROXY_D2D1` in D2DProportionalizer.cpp).

> Also, for proxies, if i want to make one I need to add every function or i can only add the ones my game uses?

Technically it's enough to only provide the functions your game uses, but for broader usage, it's of course safer to provide all of them. The d3d9 files in AlternateProxies were incomplete, but should be complete now.

**Comment by Arata12** [comment]
Crash before showing modified text, also, i don't if this is related but my infile is Shift-jis, but my output file is ANSI
![image](https://user-images.githubusercontent.com/34563333/166409466-8fba54c9-7f81-4098-b033-b49faf8404c1.png)
[issue.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8608433/issue.zip)

**Comment by arcusmaximus** [comment]
Please send an archive (.dat file) rather than one script file - or tell me which tool I can use to pack .dat files myself. I tried https://github.com/vn-tools/whale-tools but it doesn't seem to work for this game.

**Comment by Arata12** [comment]
you can use https://github.com/Forlos/vn_re to pack into .dat again, /bin/acv1

[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8614100/script.zip) Modified
[script original.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8614122/script.original.zip) Original

**Comment by arcusmaximus** [comment]
The game isn't crashing because of VNTextProxy, but because the test message is too long (looks like it can be 256 characters at most). Please try shortening it.

**Comment by Arata12** [comment]
Oh, I see, my bad, now it´s working, the only issue it's this, but I don't if is because the engine or not, anyway, thanks.
>  (looks like it can be 256 characters at most)
I think it's less, my text was around 231 characters, I guess.
![image](https://user-images.githubusercontent.com/34563333/166791275-93f43d69-5687-4916-afc8-29c21eab9215.png)

**Comment by arcusmaximus** [comment]
The extra spaces after accented characters are indeed caused by the engine. It thinks they're full-width (Japanese) characters and thus gives them twice as much space as half-width (Latin) characters. For simpler engines, VNTextProxy can fix this kind of incorrect positioning automatically - however, this one is more complicated, meaning you'd have to reverse engineer the engine, find out where it checks the character type, and patch it so that all characters are treated as half-width.

In the meantime I also checked Golden Marriage and found that it was quite easy to make custom fonts and non-SJIS characters work there as well (see above commits).

**Comment by Cosetto** [comment]
@Arata12 check [this](https://github.com/rr-/tsujidou/blob/master/README.md#caveats), a note from the guy hacked tsujidou

**Comment by Arata12** [comment]
> @Arata12 check [this](https://github.com/rr-/tsujidou/blob/master/README.md#caveats), a note from the guy hacked tsujidou

Thanks, I'll check it later.

Tested with Golden Marriage.
It's working. Thanks for your help.

![image](https://user-images.githubusercontent.com/34563333/166864329-3f574577-3410-45eb-b9e5-91c96f888a96.png)

**Comment by Cosetto** [comment]
Hm, not sure if this will work for Whale engine. Why don't we change the inserted text to full-width and use vntextproxy to change the letters back to half-width like SystemNNN and Csystem, well, if that could fix the characters limit.
