### ISSUE TITLE
Request: TmrAdvSystem

### ISSUE THREAD

**Issue by xenei** [arcusmaximus/VNTranslationTools#46]
Hello, Is it possible to add support for TmrAdvSystem game-engine? the archive format is .pac and script files are format-less, though Garbro shows them as .srp and .var for system files; which also has some important text for the game, this game engine is mostly used by Lune titles - https://vndb.org/p490 - 
Here's a reference - [Link](https://github.com/AyamiKaze/ext_TmrHiroADVSystem_text/blob/main/ext_TmrHiroADVSystem_text/TmrHiroADVSystemProject/TmrHiroADVSystemProject.cpp)
The attached link for the reference can only extract but can't repack  to .srp and .var
EDIT: Here's an sample of the script files and system files -
[garbro.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8620447/garbro.zip)
Thank you.

**Comment by arcusmaximus** [comment]
Support implemented. I didn't test it ingame, so let me know if everything works (line breaks, choice screens...)

As @AtomCrafty wrote, using messages as dictionary keys is a bad idea because there will always be cases where a (proper) translator wants to have different translations for lines that are identical in the original.

**Comment by xenei** [comment]
Everything seems to be working, choices, text etc, but word-wrap is not working
The Line-break code should be \n  ,  I tried both Mono and proportional, but none seems to make any difference
Choices is also fine -
![image](https://user-images.githubusercontent.com/91423244/167253195-f423ec77-ad51-4533-99a0-4df147417ad2.png)

**Comment by arcusmaximus** [comment]
Wordwrapping added (monospace), please try again.

**Comment by xenei** [comment]
Unfortunately, it still doesn't seem to be working, decreasing or increasing Monospace char value doesn't make any difference
Though manually adding \\n to script seems fine

**Comment by arcusmaximus** [comment]
Forgot to also apply the wordwrapping to narration lines (only did it for dialogue at first)... Should work now.

**Comment by xenei** [comment]
It's working, thank you very much
