### ISSUE TITLE
Request: Build a release

### ISSUE THREAD

**Issue by yuuyuki** [arcusmaximus/VNTranslationTools#49]
It's difficult for non-C# experienced users to build a release on their own.

I'm requesting a compiled release for users who may be technically experienced to use the product but not have the know-how to compile a C# project.

Please let me know if there is already an executable in one of the folders that I missed out, thanks.

**Comment by Cosetto** [comment]
Install visual studio and choose to install c# after that click .sln file to open the project to build vntextpatch, remember too add freemote external. But anyway here's my [build]  (https://github.com/arcusmaximus/VNTranslationTools/issues/33#issuecomment-1100780457) , it's not too outdated if the engine is kirikiri or bgi. Vntextpatch always update so I think arc_ won't make any release, so you have to compile it yourself.

**Comment by Cosetto** [comment]
Here's the latest build
[Uploading VNtextpatch.zip…]()

**Comment by arcusmaximus** [comment]
Build is now available (along with an easy system for me to create more). See the "Releases" link on the right side of the overview page.
