### ISSUE TITLE
.ws2 Failed 

### ISSUE THREAD

**Issue by WOOVYWOOVY** [arcusmaximus/VNTranslationTools#51]
I use the release v0.0.1 

![Screenshot (60)](https://user-images.githubusercontent.com/81911243/170057005-4e5f3a6d-0e0e-4318-bd3b-d788e0247db6.png)
 
And Failed.

![Screenshot (61)](https://user-images.githubusercontent.com/81911243/170057348-66f06f5a-b044-4532-9ecf-5649177a587b.png)

Pls help,thank you !

**Comment by Cosetto** [comment]
please send the script too

**Comment by WOOVYWOOVY** [comment]
[Rio~.arc.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8766835/Rio.arc.zip)
 
There you go^^

**Comment by Cosetto** [comment]
Oh yeah, Rio.arc too if don't mind(just in case)

**Comment by WOOVYWOOVY** [comment]
[Rio.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8768162/Rio.zip)
 
There there it's from If My Heart Had Wings Flight Diary.

**Comment by Cosetto** [comment]
What tool did you use to extract Rio.arc? The script you sent seem to be encrypt or something, but I use GARbro to extract Rio.arc you sent and it seems to be readable.
![image](https://user-images.githubusercontent.com/81801486/170239240-987f6086-1195-41d6-a737-e0114e0d3646.png)
Anyway this should be the right script 
[Rio.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8770143/Rio.zip)

**Comment by WOOVYWOOVY** [comment]
I use arc_unpacker,and also now i'm using Garbro(i never used it before lol) and finally can,thanks man.

**Comment by arcusmaximus** [comment]
Fixed (see v0.0.2 release).

**Comment by WOOVYWOOVY** [comment]
Great, thanks!
