### ISSUE TITLE
Artemis Engine implement ASB script

### ISSUE THREAD

**Issue by MishaIac** [arcusmaximus/VNTranslationTools#52]
Hello. Is it possible to implement the .abs script found in Artemis Engine? I know that VNTextPatch already has support just plain Artemis .txt, but these scripts are compiled. I personally never saw these scripts in any of the VNs in that engine, but at least one has them and it's a new version of Aiyoku no Eustia on Artemis Engine.

Here sample: [aiy00010.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8781358/aiy00010.zip)

I studied the script a bit, and found that each line of text has a data tag preceded by a string size in bytes. Through the hex editor I made the string longer, and then changed the size of the string. As a result, the game does not crash, and it displays the changed string, which is longer than the original string (if you do not change the size of the string, the game crashes, which is logical). About other strings, such as character names and choices I do not know, but I think there is also just a string size. All text is in UTF-8.

**Comment by MishaIac** [comment]
Well, the problem is partially solved. Inside the .pfs archive I found one .lua script that has a function called `print`. In .asb file it is called every time when need to display text on the screen. So I can change this function so that it returns a translated string instead of the original string. Before that, I need to parse all the strings by going through the whole game, and it's very inconvenient. I could not find the functions responsible for names or choices.

As for exe file, it uses the most common unmodified executable for the Artemis engine. Apparently, support for .asb files was always there, just wasn't used. In any case, here is the exe file: [Artemis.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8881846/Artemis.zip)

I have the game itself, but it has a very large size, and given that I have a weak Internet, it will take a very long time to upload it.

**Comment by MishaIac** [comment]
Ah, I found the link where I got the game from. Here's the [link](https://drive.google.com/file/d/1mCq5aeBLTXItmpWayuPKUBtRw35Xo42W/view).

**Comment by arcusmaximus** [comment]
.asb support now available.
