### ISSUE TITLE
Request: Support for Mware

### ISSUE THREAD

**Issue by Presi5** [arcusmaximus/VNTranslationTools#53]
Hello. Could you please add support to the tool for .nut files in the Mware engine? That is the new engine used by Nitro+'s recent games (and not so recent). I'm going to attach some scripts fore reference. Again, thank you.
[nut.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8882674/nut.zip)

**Comment by Presi5** [comment]
Additional info: in this case, it seems that the scripts are in UTF8, but I'm not sure if this apply to all games. At least English versions of this engine and this company (Jast) use UTF, but Japanese versions with the same engine use SJIS. I thought that you may know that, just in case.

**Comment by AtomCrafty** [comment]
For reference: MWare uses Squirrel as the embedded VM. The language specification and additional info can be found on http://squirrel-lang.org.

**Comment by Cosetto** [comment]
Another reference: https://github.com/marcussacana/MwareStuff/blob/master/NUTEditor/NUT.cs

**Comment by arcusmaximus** [comment]
Support implemented with UTF8 encoding. If you ever need SJIS, you can change the `Encoding` property in MwareScript.cs to `StringUtil.SjisTunnelEncoding`.

**Comment by Cosetto** [comment]
Can you also add support for English script like this one from Muramasa?
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8955238/script.zip)

**Comment by arcusmaximus** [comment]
That one used an entirely different convention (doesn't call the "Print" function but instead populates a large array). Support for that one is now available as well.
