### ISSUE TITLE
Usage Manual

### ISSUE THREAD

**Issue by OwenArcrux25** [arcusmaximus/VNTranslationTools#6]
Hello, I want to ask how to use this tool.
Should I download your whole code and place them somewhere? I tried that but only managed a not recognized as an internal or external command. Which file should I execute? Should I add your code folder to PATH etc? Platform: Windows

**Comment by arcusmaximus** [comment]
The code can't be executed directly. You need to open VNTranslationTools.sln in Visual Studio and compile the projects to get .exe and .dll files.
