### ISSUE TITLE
BGI with The given key was not present in the dictionary on Amairo Chocolate

### ISSUE THREAD

**Issue by OlegSea** [arcusmaximus/VNTranslationTools#60]
After I tried to manually extract the scripts using GarBro and running the script on them, it gave me the `The given key was not present in the dictionary.` error. [Here](https://drive.google.com/file/d/1uov_IpmrXpi_d5FMQU0BAQaALbuWedHD/view?usp=drivesdk) and [here](https://drive.google.com/file/d/1SHOtuRh6RyAqsqkIGBB1t0YhXjhy8TUA/view?usp=drivesdk) are the extracted scripts if it can help. 
UPD: real scripts this time

**Comment by OlegSea** [comment]
Also after I tried to manually extract the scripts using GarBro and running the script on them, it gave me the `The given key was not present in the dictionary.` error.

**Comment by OlegSea** [comment]
> scripts
[Here](https://drive.google.com/file/d/1ytTSRFSfkYH6dM-dNYmQRkIj9fsvET4M/view?usp=drivesdk) are the scripts if it can help.

**Comment by OlegSea** [comment]
Also a question, not necessarily related. Is there a way to pack those scripts back into .arc files?

**Comment by Cosetto** [comment]
VNtextpatch doesn't support to extract text from .bsi format, only extensionless files from data01xxx.arc for now, which is the first one you sent

**Comment by OlegSea** [comment]
Writing my own script it is then

**Comment by OlegSea** [comment]
Okay, Amairo Chocolate 2 uses the format that should work. Yet I still get the `The given key was not present in the dictionary.` error. [here](https://drive.google.com/file/d/1DY3_bFaEvx6lJaH8EOrzC1NVFkz2pVrM/view?usp=sharing)

**Comment by Cosetto** [comment]
I mean just leave the scripts(extensionless files) there and arc_ will add more opcode when he's back

**Comment by OlegSea** [comment]
[Here](https://drive.google.com/file/d/1QGO90EtLa0NUGq_1wCLrOj5SEZarCRZY/view?usp=drivesdk) you go

**Comment by arcusmaximus** [comment]
Fixed.
