### ISSUE TITLE
(Krkr) The type initializer for 'PerTypeValues`1' threw an exception 

### ISSUE THREAD

**Issue by kokoiro** [arcusmaximus/VNTranslationTools#61]
Hello.

I tried to extract the text from some Krkr, but I keep getting this error. Tried with KoiKuma, Mr. Sister and Haramase.
[Here's a sample script](https://cdn.discordapp.com/attachments/687043665289412705/996284082537365534/a02_rir_00.ks.scn).

Am I doing something wrong? (Would'nt be a surprise tho lol)

Thank you.

**Comment by arcusmaximus** [comment]
Caused by a missing DLL - fixed.

**Comment by kokoiro** [comment]
@arcusmaximus I want to extract the English text. What do I need to change in code?

**Comment by kokoiro** [comment]
Nvm, got it. Would be useful do this without changing the code in the future. Thank you anyway!

**Comment by kokoiro** [comment]
@arcusmaximus I'm using google sheets to edit the files, but got these symbols after repacking:
![imagen](https://user-images.githubusercontent.com/59524166/178548473-1f88e59e-666b-4ca1-8d60-ea9387d2727a.png)

After checking with Scn Editor from Marcus, I see that there are words joined together, and when I copy them, they look like this:
He
llo.

It is as if there is something between he and llo that forms an invisible symbol.

**Comment by Cosetto** [comment]
> @arcusmaximus I'm using google sheets to edit the files, but got these symbols **after repacking**: ![imagen](https://user-images.githubusercontent.com/59524166/178548473-1f88e59e-666b-4ca1-8d60-ea9387d2727a.png)
> 
> After checking with Scn Editor from Marcus, I see that there are words joined together, and when I copy them, they look like this: He llo. ![imagen](https://user-images.githubusercontent.com/59524166/178549396-181e279b-fb2a-4885-87d8-e13930fe999e.png) (Should be mi ca) ![imagen](https://user-images.githubusercontent.com/59524166/178550542-91bae366-f9e1-4620-b77d-d01b31fd1386.png) (Should be mos a)
> 
> It is as if there is something between he and llo that forms an invisible symbol (or linebreak?).
> 
> ![imagen](https://user-images.githubusercontent.com/59524166/178551421-4c5d1e51-3e13-4e1e-8347-b081e0f0303b.png)
Try with json format

**Comment by kokoiro** [comment]
@Cosetto Thank you. It seems adding more characters fixed that.
