### ISSUE TITLE
Index was out of range. Engine CSystem Cyberworks

### ISSUE THREAD

**Issue by sakurahana90** [arcusmaximus/VNTranslationTools#62]
I'm sorry if this counts as double post as I also posted this in CSystem repo.

I tried use VNTranslationTools to extract text from Yumekoi Tensei from Tinkerbell which has CSystem and encountered this warning:

C:\VNTextPatch>VNTextPatch.exe extractlocal C:\yumekoi C:\yumekoi\script.xlsx --format=csystem
Arc00.dat
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex

I also attach the file, perhaps there's a hint to make a change in the code to make the tool works with this game
[Arc00.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9098685/Arc00.zip)

Thank you

**Comment by Cosetto** [comment]
Maybe the scenario is encrypted. Why don't you try using GARbro to check cg archives, double click on it and choose no encryption (if Garbro gives you encryption scheme). If you can't view the cg then it must be encrypted

**Comment by Cosetto** [comment]
Also vntextpatch can't extract Arc00, only .csa you get from Arc04.dat

**Comment by sakurahana90** [comment]
Sure, here's the files
[yumekoi.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9101201/yumekoi.zip)

**Comment by arcusmaximus** [comment]
Looks like this game uses an older version of the engine where the strings didn't come with an encryption key yet. VNTextPatch now supports this older format too.

Concerning the "difference" between .a0 and .csa:
Files inside CSystem archives don't actually have an extension, only an ID, a type code (`a` for scenarios) and a subtype code (`0` for scenarios). This means you have to make up an extension yourself - I went with .csa for my tools, whereas GARbro apparently went with .a0.

I changed both CSystemArc and VNTextPatch to use .a0 instead for consistency.
