### ISSUE TITLE
About xlsx format

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#63]
It seems like xlsx format doesn't recognize line-break character like "\n". The original scripts should have \n at the end of line but xlsx just break the scripts
This is with .json format
![image](https://user-images.githubusercontent.com/81801486/180604434-6c1bbff9-25ab-4b00-a477-1d3904e0d8fb.png)
![image](https://user-images.githubusercontent.com/81801486/180604442-060941ab-4f01-4fc1-958b-4878a737c271.png)
This is with .xlsx format
![image](https://user-images.githubusercontent.com/81801486/180604471-e2800202-3891-4607-af3a-943c84905e52.png)
![image](https://user-images.githubusercontent.com/81801486/180604514-569817f9-10a3-4348-b855-e05f952162f7.png)
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9173740/script.zip)
This is BGI engine, I dunno if that happens to other engines too

**Comment by arcusmaximus** [comment]
In Excel files, you're supposed to insert actual line breaks with Alt-Enter rather than typing `\n`.

**Comment by Cosetto** [comment]
It works but those sentences need to be in same place
![image](https://user-images.githubusercontent.com/81801486/180898770-370b09dd-1248-4ba1-b724-e525a32c65f4.png)
![image](https://user-images.githubusercontent.com/81801486/180898813-6728b4e6-cd07-451d-9acb-09eae3c87fe9.png)

**Comment by arcusmaximus** [comment]
If I remember right, the lines in the screenshot are not displayed in one go ingame, but have a click-wait inbetween. In that sense, they're two separate messages and the current behavior (splitting them into different Excel cells) is correct.

**Comment by Cosetto** [comment]
Can we get around this somehow since there're too many lines like that, I told my friend to use json format when waiting for new update

**Comment by arcusmaximus** [comment]
> Can we get around this somehow

I'm afraid not... If messages are getting split up in the extracted Excel/JSON file, that means there's code between them in the game file: to make the game wait for a click, maybe do a scene transition and so on. To merge those split messages together, that code would have to removed, which would cause all kinds of problems.

> I told my friend to use json format when waiting for new update

There's really no difference between Excel and JSON content-wise. Both have the messages split up in the same way, and both have line breaks in the same places. The only difference is that one has real line breaks and the other represents them with an escape sequence (\n).
