### ISSUE TITLE
Request for .pac support

### ISSUE THREAD

**Issue by thewonderful24** [arcusmaximus/VNTranslationTools#64]
Hello, I'm interested in doing a translation of [a game](https://vndb.org/v18722) and I am trying to find a way to extract the text, but I haven't been able to find a working tool. The game uses a .pac file format which I don't see in the current list. I asked around on a forum and they said the engine looks like Softpal, which is supported, but I'm not familiar enough with these engines to confirm that or identify what slight changes might have been made to the file formats, as the softpal extension is listed as script.src. If anyone could point me in the right direction or offer assistance I would really appreciate it. 

I've attached an image of all the game files in case that helps identify the engine. 
![File List](https://user-images.githubusercontent.com/110351501/182040679-02e6aa91-f709-4145-8a78-386b4f518567.jpg)

**Comment by thewonderful24** [comment]
On further investigation it seems like .pac might be an archive format, similar to .zip. If anyone knows of a good way to extract them and find the script file please let me know.

**Comment by thewonderful24** [comment]
I was able to extract the script.src and text.dat files from the pac. Working on translating now. A quick question, once I'm done, which column in the excel sheet gets imported into the game data? TL or TLC? I'm assuming TL means translation, is TLC "translation complete"?

**Comment by Cosetto** [comment]
> I was able to extract the script.src and text.dat files from the pac. Working on translating now. A quick question, once I'm done, which column in the excel sheet gets imported into the game data? TL or TLC? I'm assuming TL means translation, is TLC "translation complete"?

TLC is Translation Check which is for checking the translation and vntextpatch will insert from Edit>TLC>TL. If Edit, TLC column both have translation, it will go for Edit column; if Edit column is blank then it will go for TLC column and so on
