### ISSUE TITLE
Specified argument was out of the range of valid values.(ADVHD)

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#65]
[Script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9265111/Script.zip)
I got this when trying to insert the script. There's also something about the script of official English release, like they have "\d" on every dialogue lines and when in game they become **"**
![image](https://user-images.githubusercontent.com/81801486/182999144-04588450-6b92-4135-a42a-d353b62d141e.png)

**Comment by arcusmaximus** [comment]
Error fixed. I don't know if that `\d` escape sequence does anything that a regular `"` doesn't, so I'll leave that one as it is. You can always do a search-replace yourself.

**Comment by Cosetto** [comment]
thanks

**Comment by Berthog** [comment]
Sorry arc, can you also check this one please? It's advhd script format too and it present the same message error in the insertion process. 
[comun.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9457601/comun.zip)
