### ISSUE TITLE
Japanese emphasis dot cut the script

### ISSUE THREAD

**Issue by Sisulizer** [arcusmaximus/VNTranslationTools#67]
Example: **「[・]最[・]期には――痛いの、全部消えるみたいだから」**
![image](https://user-images.githubusercontent.com/91543117/185669433-e4d3b9b7-ae6f-4303-a080-82b0f19289dd.png)
Can you make it into a line?
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9383977/script.zip)

**Comment by arcusmaximus** [comment]
Every Kirikiri game has its own way of specifying ruby text, so there's really no way of supporting it universally. But sure, I added the command for this particular game.

**Comment by Sisulizer** [comment]
Thank you

**Comment by Sisulizer** [comment]
@arcusmaximus There's also this line: **「[resetwait]たぶん、私と仲良くしてるからだと思うけど――[wait mode=until time=4545][chr_del_jump name=恵璃 time=200]ねっ」**, I tried to modify this line 
![image](https://user-images.githubusercontent.com/91543117/185785923-9878b920-3fd5-4fd4-a2da-d781878a9c43.png)
But it still splits into 2 lines 
![image](https://user-images.githubusercontent.com/91543117/185785943-b7330f8f-12c5-4485-9437-42328cc025fa.png)

**Comment by Sisulizer** [comment]
Actually never mind, if I do that, it will extract other unnecessary lines
