### ISSUE TITLE
Request for more OP codes for a new BGI game

### ISSUE THREAD

**Issue by PoisonPyte** [arcusmaximus/VNTranslationTools#68]
Hello, I have a script file for a recently released BGI game where one of the files couldn't be extracted.
"The given key was not present in the dictionary" 
[prologue_02.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9388073/prologue_02.zip)

**Comment by arcusmaximus** [comment]
Please send me the game's ._bp files so I can find all the new opcodes rather than just the ones used in this script.

**Comment by PoisonPyte** [comment]
Sorry, here they are. 
[BPfiles.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9388895/BPfiles.zip)

**Comment by arcusmaximus** [comment]
Looks like the ._bp virtual machine received new opcodes too, which means I'll first need to disassemble the new engine version and extend BgiDisassembler (which will be for whenever I manage to work through the other requests that have been piling up). Please let me know which game this is for.

**Comment by PoisonPyte** [comment]
This is from the trial version of Houkago Cinderella 2. The full game won't be out until September and I still have to translate the first game so please take your time.
I'm not sure if the final game engine will have any differences or not but I'll include a link to the trial download page for now.
https://www.hook-net.jp/houkago2/trial.html

**Comment by PoisonPyte** [comment]
The first game got taken down so we will no longer be working on the second game. Thank you for your help earlier in the year in adding support for the first game's script.
