### ISSUE TITLE
About cyberwork

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#7]
So I can dump the script from Csystem(tinkerbell)? but how can I pack it back to the .dat format? Or does the game can read from specific folder?

**Comment by arcusmaximus** [comment]
I uploaded my archive unpacking/repacking tool: https://github.com/arcusmaximus/CSystemTools
Please see if it works for you.

**Comment by Cosetto** [comment]
Thanks it works, if possible can you make it pack into new archives like patch01.dat patch02.dat, I think it can read from those 
![image](https://user-images.githubusercontent.com/81801486/146288480-668fa0f9-9ec8-4178-8f62-aa7085f34939.png)

**Comment by Cosetto** [comment]
I forget to ask what should I rename the d2d1.dll to make it work?

**Comment by arcusmaximus** [comment]
I don't know yet if and how those patch files work, so the tool doesn't support them yet. Feel free to create a ticket for it in the CSystemTools repository.

d2d1.dll doesn't need to be renamed, but you do need to change the code to enable its Direct2D functionality (dllmain.cpp). By default, it only does GDI.
