### ISSUE TITLE
How to reinsert text. ( ADVHD )

### ISSUE THREAD

**Issue by WOOVYWOOVY** [arcusmaximus/VNTranslationTools#70]
Okay so, i already extracted the files, and translated one of the ws2 script to test.

Using the command, VNTextPatch.exe extractlocal <folder containing original game files> script.xlsx

Done.

Then VNTextPatch.exe insertlocal <folder containing original game files> script.xlsx <folder to receive patched game files>

Next i got the results to be the .json as the patched game files, and everything went smoothly.

![Screenshot (64)](https://user-images.githubusercontent.com/81911243/187038952-26e336bf-004a-4a6d-b05b-7b8d5562fb26.png)

But then how to insert it back to .ws2? Sorry if this is a stupid question, i'm really a normie :)

**Comment by Cosetto** [comment]
You're missing output folder
For example: To insert from json format you do this : vntextpatch insertlocal input script output
Same thing with xlsx format: vntextpatch insertlocal input script.xlsx output
Or simply use run this batch file, put it in same folder with vntextpatch.exe and run create_folder.bat first
[vntext_batch.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9438340/vntext_batch.zip)

**Comment by WOOVYWOOVY** [comment]
Okay i'll try, thanks!

**Comment by WOOVYWOOVY** [comment]
AH, i found out why, inside the original game script folder, there's another .json files other than the .ws2, idk why , and that made the output folder also .json files.

I deleted the .json files in the original game script and finally got the output, next time i'll try using the batch file, thank you!

**Comment by WOOVYWOOVY** [comment]
Anyway Cosetto, any idea how to use VNTextProxy, i already put the font.ttf in the game .exe folder and also d2d1.dll from the release there. But did nothing. Thanks!

**Comment by Cosetto** [comment]
You need to know what proxy does the game preference to, for example like BGI, it can use either d3d9 or dinput8
![image](https://user-images.githubusercontent.com/81801486/187053653-4220a8f0-cdbb-4112-8efd-cd9b337356fc.png)
In your case, if I'm not wrong advhd preference d3d9

**Comment by WOOVYWOOVY** [comment]
Um, nothing happened.

![Screenshot (66)](https://user-images.githubusercontent.com/81911243/187065134-392d1465-36ad-4ab0-9cc8-fd1961e047be.png)
![Screenshot (67)](https://user-images.githubusercontent.com/81911243/187065420-9bfeb4bc-cc59-43cd-9530-20e1e1e69427.png)


Still the same.

Do i need to change the .dll code first? Since i thought by just put both one of the dll and ttf file in one folder in the .exe folder will do. I'm really noob idk how...sorry.

**Comment by Cosetto** [comment]
Try winmm.dll
If nothing happen too then you're not wrong, the problem is my friend said the proxy doesn't work only for games from 2017 forward.
Well, I found [another hook](https://github.com/YuriSizuku/GalgameReverse/blob/master/src/advhd/advhd_patch.c) by the Chinese, it might work for newer game

**Comment by WOOVYWOOVY** [comment]
... Simply, all i need to do is change the MSGOTHIC.TTF to MS Gothic.TTF, done, i put both d3d9.dll and d2d1 too...

**Comment by WOOVYWOOVY** [comment]
SO THANK YOU again!

**Comment by Cosetto** [comment]
> ... Simply, all i need to do is change the MSGOTHIC.TTF to MS Gothic.TTF, done, i put both d3d9.dll and d2d1 too...

doesn't need d2d1
