### ISSUE TITLE
Qlie bug: Invalid char found at index

### ISSUE THREAD

**Issue by JackOfBadTrades** [arcusmaximus/VNTranslationTools#71]
Game tested: Walkure Romanze and Walkure Romanze More&More.

Issue: It seems that Ricotta's games make the tool crash. I extracted the script files, used the tool on the scenario folder, and [this error](https://files.catbox.moe/93bthc.jpg) popped up.
If I'm reading [this](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/QlieScript.cs) correctly, it seems that the QLIE tool is programmed to ignore lines starting with `@` and `/` , yet it doesn't do it in this specific case.

Attaching script files: 
Walkure Romanze
https://files.catbox.moe/14av8k.zip
More&More
https://files.catbox.moe/c6hws3.zip

**Comment by Cosetto** [comment]
Well, it seems like if you want to extract to excel sheet, you have to put all scenario files in a single folder like this 
![image](https://user-images.githubusercontent.com/81801486/188814032-94a987ca-a8ae-4b14-abe5-6ae311716658.png)

**Comment by Cosetto** [comment]
I guess that is because Qlie's script has different types 
![image](https://user-images.githubusercontent.com/81801486/188845063-4ab9102a-02f0-45d4-a1e7-a9cff30eeb69.png)
I assume that is new one and Walkure's script is old one
![image](https://user-images.githubusercontent.com/81801486/188845468-f7ce9a52-f103-4728-95da-65241f0b876f.png)

**Comment by Cosetto** [comment]
There's also alternative tool for Ricotta: [link](https://github.com/leoFitz1024/Asuna/tree/997907d101dbf2562b9817541bcf5be4ab531caf/Source/Hooks/PrincessLover/ScriptEditor). But I'm not sure how to compile this one

**Comment by JackOfBadTrades** [comment]
Ah my thanks, but I'm already using a tool based on [Marcus's SacanaWrapper](https://github.com/marcussacana/SacanaWrapper) that uses his [QLIE filter](https://github.com/marcussacana/AIO/issues/1). I was just looking for alternative tools since the thing I did is the clunkiest thing in the universe, that somehow only I can run but not others.

**Comment by Cosetto** [comment]
You can use this too, all written in python 
[qlie-script-tool.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9508029/qlie-script-tool.zip)

**Comment by arcusmaximus** [comment]
This alternative message style is now also supported.
