### ISSUE TITLE
Issues with SJIS tunneling (Kaguya Game)

### ISSUE THREAD

**Issue by tynime** [arcusmaximus/VNTranslationTools#72]
Hello, I can't get SJIS tunneling to work on this game from Kaguya [Mamagoto](https://vndb.org/v26530)
Is there any solution?
[sjis_ext.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9550032/sjis_ext.zip)

**Comment by arcusmaximus** [comment]
Where could I "acquire" the game for testing?
Could you send a translated scenario and let me know which VNTextProxy DLL you used?

**Comment by Cosetto** [comment]
> Where could I "acquire" the game for testing? Could you send a translated scenario and let me know which VNTextProxy DLL you used?

You can try on Mama x Holic or trial version of any games from Bare&Bunny, they are all same. The engine should preference d3d9.dll but it doesn't. [This hook](https://github.com/marcussacana/StringReloads/tree/master/StringReloads)'s d3d9 works with CreateFontIndirectA of the engine

**Comment by arcusmaximus** [comment]
Fixed. (Image below: font set to Arial, text uses non-SJIS "é")

![image](https://user-images.githubusercontent.com/133129/197356824-c1a47756-8521-4f22-bb24-03075d5ecbbd.png)

The game's .exe doesn't (directly) import d3d9.dll, so that one won't work. version.dll works, however.

**Comment by Cosetto** [comment]
Ok I take my words back, looks like not all game are same. I tested on [Mamagoto](https://vndb.org/v26530) and it crashed, I guess it's an older version

**Comment by arcusmaximus** [comment]
Reopening to investigate Mamagoto.

**Comment by arcusmaximus** [comment]
The Mamagoto trial also works for me with the current (v0.0.18) version.dll:

![image](https://user-images.githubusercontent.com/133129/197625318-f5a93dfd-5a76-4ffe-94bd-400df41c7b26.png)

**Comment by Cosetto** [comment]
> The Mamagoto trial also works for me with the current (v0.0.18) version.dll:
> 
> ![image](https://user-images.githubusercontent.com/133129/197625318-f5a93dfd-5a76-4ffe-94bd-400df41c7b26.png)

Mine crashed when I clicked the start button, but it worked normal if I load 

https://user-images.githubusercontent.com/81801486/197669710-4150088e-e31b-4b8f-85df-f4f8e44819de.mp4
