### ISSUE TITLE
Error reinserting translation text(softpal)

### ISSUE THREAD

**Issue by fushi002** [arcusmaximus/VNTranslationTools#74]
Translated text will not be reinserted normally.
As I checked it carefully, it seems that the text insertion itself is not working properly
Please check.

[Yuurei.zip](https://drive.google.com/file/d/1KmQ5WTe8iRQL4QcCc3vmW63NOzoLH4M-/view?usp=sharing)

Game information: https://vndb.org/v37240

**Comment by arcusmaximus** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/133129/197349513-a7297340-c612-461e-9bb8-993da16ba19b.png)

What's the problem exactly?

**Comment by fushi002** [comment]
Oh, it was my illusion
I'm sorry for bothering you
