### ISSUE TITLE
Whale Regex doesn't catch lines with … at beginning

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#77]
Example
![image](https://user-images.githubusercontent.com/81801486/196016312-6c4c22a2-3594-4a19-874d-b2505a9f23b8.png)
What should I add to this line?
![image](https://user-images.githubusercontent.com/81801486/196016327-cb91a2ef-7dc0-41ce-b29c-6dd52544dd4e.png)

**Comment by arcusmaximus** [comment]
Reopening so it can be fixed in VNTextPatch itself

**Comment by Cosetto** [comment]
Also added:
**			if (line.StartsWith("―"))
				return GetMessageRanges(line, lineStartPos);**
![image](https://user-images.githubusercontent.com/81801486/196364836-ae6b08d7-1188-4563-8390-0d1f96bf68b3.png)
And:
**@"^(?:【(?<name>.+?)(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?(?:,\w+)?】)?(?:(?<message>.+)|「(?<message>.+)」|(?<message>（(?:.+)）))$");**
![image](https://user-images.githubusercontent.com/81801486/196364669-c661fa9d-d6d0-4b3f-9637-952e02c93dc5.png)
![image](https://user-images.githubusercontent.com/81801486/196364975-e3de2b91-cfae-4a93-907d-384c4ece56d5.png)

**Comment by Cosetto** [comment]
And I got error when compiling vntextpatch if [this line](https://github.com/arcusmaximus/VNTranslationTools/blob/b34598ab56099728fae80cffddca500f06ee4c82/VNTextPatch.Shared/Util/WordWrapper.cs#L124) is `public`

**Comment by arcusmaximus** [comment]
Fixed.
