### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by bregassa** [arcusmaximus/VNTranslationTools#8]
It's caused by Freemote, can you share the freemote folder you use?
https://imgur.com/a/YPzMeQ4

**Comment by bregassa** [comment]
or is it caused by something else?

**Comment by arcusmaximus** [comment]
If you clone the repository to your harddrive with a Git client rather than simply downloading the source code from the Github website, you should have all the necessary files. Apart from that, please make sure you have the .NET Framework 4.8 SDK installed.

**Comment by bregassa** [comment]
> If you clone the repository to your harddrive with a Git client rather than simply downloading the source code from the Github website, you should have all the necessary files. Apart from that, please make sure you have the .NET Framework 4.8 SDK installed.

So I'm done with issue above, now I have another issue where the cmd would open then close right away. Can you upload your build instead?

**Comment by bregassa** [comment]
So somehow I figure it out how to open the program, now it give me this

F:\Offline\Visual` Novel\[MTL] Machine Translation tool\VNTranslationTools\Build\Debug>VNTextPatch extractlocal scenario script.xlsx
The file could not be accessed. Try one of the following:

? Make sure the specified folder exists.
? Make sure the folder that contains the file is not read-only.
? Make sure the filename and folder path do not contain any of the following characters:  <  >  ?  [  ]  :  | or  *
? Make sure the filename and folder path do not contain more than 218 characters.

I'm trying to extract ybn file

**Comment by bregassa** [comment]
I achieve success extraction, thank you man awesome work

**Comment by arcusmaximus** [comment]
Good to hear you got it working :)

**Comment by arcusmaximus** [comment]
Then again, I saw in your folder path that you intend to create a machine translation.

![image](https://user-images.githubusercontent.com/133129/146812715-53bbe30a-5b1a-4d85-aaf0-49dda9eabd3b.png)

**Comment by bregassa** [comment]
> Then again, I saw in your folder path that you intend to create a machine translation.
> 
> ![image](https://user-images.githubusercontent.com/133129/146812715-53bbe30a-5b1a-4d85-aaf0-49dda9eabd3b.png)

loll.. trust me MTL quality is good these days, Sugoi Offline Translator is already or maybe better than deepL
