### ISSUE TITLE
Some non-extractable strings on the Majiro script

### ISSUE THREAD

**Issue by medAndro** [arcusmaximus/VNTranslationTools#80]
![start1](https://user-images.githubusercontent.com/88672474/197702396-03e19007-a48b-417f-ad65-a157dcbf87fa.PNG)

![start3 복사](https://user-images.githubusercontent.com/88672474/197703424-4e33fb23-76e8-4569-8eab-ffe37ce64e3f.jpg)

**script file :  [start.mjo.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9857789/start.mjo.zip)**
Game : サナララR (Sanarara R)

I found the "現在は選択できません" string encoded in shift-jis as a hex editor.
And when I replaced it with a Korean string(현재는 선택불가) encoded through euc-kr, I found that it changed.
However, the VNTextPatch tool cannot extract a string.

Attach additional scripts for the same issue. ↓
![캡처](https://user-images.githubusercontent.com/88672474/197852261-0ff85752-daed-4c33-8f86-5485d82811ff.PNG)
**script file :  [1_02.mjo.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9862882/1_02.mjo.zip)**
神の使い（但し自己脳内で）

**Comment by arcusmaximus** [comment]
Fixed.
