### ISSUE TITLE
Some string extractions are still missing from the Majiro

### ISSUE THREAD

**Issue by medAndro** [arcusmaximus/VNTranslationTools#81]
First of all, thank you for fixing #79 and #80 issues

Thankfully, I was able to extract and modify the string "現在は選択できません". string in **[start.mjo](https://github.com/arcusmaximus/VNTranslationTools/files/9857789/start.mjo.zip)**
However, "ゲームを終了します。よろしいですか？" sentences are not extracted from the same file. 
Perhaps there are more strings that are not extracted from other scripts.

![1](https://user-images.githubusercontent.com/88672474/198355274-efb9fdbe-e233-4c93-922c-912fe74ffa7b.PNG)

In addition, all multiple choice string message are not extracted.
below screenshot  shows **[1_02.mjo](https://github.com/arcusmaximus/VNTranslationTools/files/9862882/1_02.mjo.zip)** script with Multiple choice strings.
(I extracted it by euc-kr encoding because of #75 korean glitch issue.)

Example of unextracted multiple choice strings in **[1_02.mjo](https://github.com/arcusmaximus/VNTranslationTools/files/9862882/1_02.mjo.zip)**
◆神の使い（但し自己脳内で） 
◆絶対に不可能っぽいことを言ってみ 
◆椎名さんだっけ？
◆ボケてみる

![2](https://user-images.githubusercontent.com/88672474/198362815-a8ea6ba9-20a1-4288-a0b5-6526130295ce.jpg)

**Comment by arcusmaximus** [comment]
Fixed. VNTextPatch already had support for Majiro choices, but I guess different games use different function names for those.
