### ISSUE TITLE
Missing messages(Softpal)

### ISSUE THREAD

**Issue by Sai-key** [arcusmaximus/VNTranslationTools#82]
When extracting all the messages to a .json file I see that the first couple of dialog lines are not getting picked up so it's not possible to translate them at the moment.

The lines not picked up are the following:
![Screenshot 2022-10-28 025716](https://user-images.githubusercontent.com/116866187/198516003-70f8cac0-69d1-497c-a0a3-03b032c2adbd.png)
![Screenshot 2022-10-28 025730](https://user-images.githubusercontent.com/116866187/198516011-5efc587b-c188-4dcd-9043-4f195ccaed2e.png)
![Screenshot 2022-10-28 025840](https://user-images.githubusercontent.com/116866187/198516022-e421b639-b302-4be7-98ac-acfdc60e3a1b.png)
![Screenshot 2022-10-28 025759](https://user-images.githubusercontent.com/116866187/198516023-74a80bb5-2b1f-4578-8433-109ca568c45b.png)
![Screenshot 2022-10-28 025820](https://user-images.githubusercontent.com/116866187/198516025-9b6bebcf-cf63-4bbc-abe6-e6effc50d95f.png)
![Screenshot 2022-10-28 025831](https://user-images.githubusercontent.com/116866187/198516027-54fe0158-47e0-4ad3-90ad-6f3442f05485.png)

Attached the SCRIPT.SRC file and TEXT.DAT
[data.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9885625/data.zip)

**Comment by arcusmaximus** [comment]
Can you also send the game's point.dat?

(As an aside, the English translation in the text.dat is somehow even more nonsensical than a machine translation, so you may want to consider getting a different translator)

**Comment by Sai-key** [comment]
Here is the original data.pac with everything inside including the point.dat :)

[data.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9892734/data.zip)

(No wories about the translation, we haven't  actually started yet. Ran the messages thourgh an MTL to check for crashes or untranslated text like it happened here)

**Comment by arcusmaximus** [comment]
> (No wories about the translation, we haven't actually started yet. Run the messages through an MTL to check for crashes or untranslated text like it happened here)

Good to hear that's not the actual TL! And yes, testing beforehand is a good idea - I've seen projects that translated everything first and *then* started figuring out how they could put it into the game...

Anyway, the missing strings are now extracted.

**Comment by Sai-key** [comment]
I'm getting another issue now that updated to your latest version.

![Screenshot 2022-10-30 032759](https://user-images.githubusercontent.com/116866187/198865771-7f767a3e-6c77-4fe0-9cbd-a5e3168f6609.png)

**Comment by arcusmaximus** [comment]
It's trying to extract point.dat, which isn't going to work. Try pointing it specifically to script.src rather than the folder containing it.

**Comment by Sai-key** [comment]
When I do that this happens:
![Screenshot_2022-10-30_040327](https://user-images.githubusercontent.com/116866187/198868070-55e4ede8-592e-42a4-93ec-797e59baa3f9.png)

**Comment by arcusmaximus** [comment]
Well, does point.dat exist at the file path it complains about?

**Comment by Cosetto** [comment]
Try using: **vntextpatch.exe extractlocal input/script.src script.xlsx**

**Comment by Sai-key** [comment]
> Try using: **vntextpatch.exe extractlocal input/script.src script.xlsx**

Big thanks, this solved my issue.
Also I really appreciate the great support ^^

**Comment by Sai-key** [comment]
> It's trying to extract point.dat, which isn't going to work. Try pointing it specifically to script.src rather than the folder containing it.

Sorry to bother you again but now there is another issue. Game crashes. Even without translating any of the lines, just extracting and then inserting without touching anything. The result (text.dat and script.src) make the game crash after opening it, but the original ones don't. No error it's shown, the game just closes.

**Comment by arcusmaximus** [comment]
I tried it out and it works for me. Make sure to:

* Run the insertion as follows: `VNTextPatch input\script.src script.xlsx data\script.src`. (This will create a new script.src and text.dat in the game's "data" folder. Copying the original text.dat will result in a crash when the first line of text is displayed ingame.)
* Make sure the "data" folder does *not* contain point.dat. VNTextPatch doesn't modify this file, and having the original point.dat in the "data" folder will result in a crash on startup.

**Comment by Sai-key** [comment]
> I tried it out and it works for me. Make sure to:
> 
> * Run the insertion as follows: `VNTextPatch insertlocal input\script.src script.xlsx data\script.src`. (This will create a new script.src and text.dat in the game's "data" folder. Using the original text.dat will result in a crash when the first line of text is displayed ingame.)
> * Make sure the "data" folder does _not_ contain point.dat. VNTextPatch doesn't modify this file, and having the original point.dat in the "data" folder will result in a crash on startup.

That worked! ^^
