### ISSUE TITLE
Missing pause menu string extract from Majiro

### ISSUE THREAD

**Issue by medAndro** [arcusmaximus/VNTranslationTools#83]
![캡처2](https://user-images.githubusercontent.com/88672474/198824033-8c53d826-cdf2-417e-822f-9ed749f2406d.PNG)
![캡처](https://user-images.githubusercontent.com/88672474/198823506-62c89c9e-6280-4a2a-83bd-6ff3d1650d23.PNG)
セーブする
ロードする
メッセージログ
コンフィグレーション
ゲームに戻る
タイトルに戻る

script: **[pausemenu.mjo.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9893322/pausemenu.mjo.zip)**

Thanks to the effort, almost all text was extracted.
There is a string that has not been extracted from the pausemenu.mjo

**Comment by arcusmaximus** [comment]
Fixed. Let's hope that was the last one then :D

**Comment by medAndro** [comment]
> Fixed. Let's hope that was the last one then :D

So far, it looks like Sanarara R's script has been extracted completely.
Thank you for your efforts. :)
