### ISSUE TITLE
Vntextpatch failed to catch half-width letter names

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#84]
![image](https://user-images.githubusercontent.com/81801486/199000655-9c96f32c-f060-4b4e-a073-aa9b56aec354.png)
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/9900734/script.zip)

**Comment by arcusmaximus** [comment]
Not going to bother fixing this, sorry. The easiest way for VNTextPatch to distinguish between attributes that need to be translated (such as names) and ones that don't (such as voice files) is looking at whether they contain Japanese text - and this approach is enough for normal cases. Sure, it doesn't support creating translations of translations, but then again, you shouldn't be doing that in the first place :)
