### ISSUE TITLE
How to pack ybn back to ypf?

### ISSUE THREAD

**Issue by bregassa** [arcusmaximus/VNTranslationTools#9]
So, I'm done with TL,
Now I need to repack ybn files to ypf
GarBro give me error "Encryption key required for archive creation", do you have any tips?

I also use other tool such as 
https://github.com/crskycode/YPF_Tool and https://github.com/fengberd/YuRISTools , both give me error when starting the game.

How do you repack ybn back to ypf the right way?

**Comment by bregassa** [comment]
it give me debug info like this :

パックファイル内のファイル
[]が
重複しています。

tl:
Files in the pack
[].
duplicated.

here's the game : https://vndb.org/v21620

**Comment by Cosetto** [comment]
> So, I'm done with TL, Now I need to repack ybn files to ypf GarBro give me error "Encryption key required for archive creation", do you have any tips?
> 
> I also use other tool such as https://github.com/crskycode/YPF_Tool and https://github.com/fengberd/YuRISTools , both give me error when starting the game.
> 
> How do you repack ybn back to ypf the right way?

This is script tool not archive tool. 
To pack back ypf use https://github.com/davidescrima9/YPF_Manager_Tool.
First use command "-p" to print the version of ypf, after that pack it "-p update1 -v [version]

**Comment by bregassa** [comment]
> > So, I'm done with TL, Now I need to repack ybn files to ypf GarBro give me error "Encryption key required for archive creation", do you have any tips?
> > I also use other tool such as https://github.com/crskycode/YPF_Tool and https://github.com/fengberd/YuRISTools , both give me error when starting the game.
> > How do you repack ybn back to ypf the right way?
> 
> This is script tool not archive tool. To pack back ypf use https://github.com/davidescrima9/YPF_Manager_Tool. First use command "-p" to print the version of ypf, after that pack it "-p update1 -v [version]

I know it's not an archive tool haha, sorry I'm just asking how to pack it back to ypf, cuz I don't know who to ask anymore.
So, I try using the tool you give, but no instruction at all give me headache haha, the program close right away after I open it.
I try using straight cmd in that folder but it give me this result. can you give me some tutorial here?

__________________

`E:\YPF_Manager_Tool-master\YPF Manager\bin\Debug>-p <bn.ypf> [options]
'-p' is not recognized as an internal or external command,
operable program or batch file.

E:\YPF_Manager_Tool-master\YPF Manager\bin\Debug>-p <bn>
The syntax of the command is incorrect.

E:\YPF_Manager_Tool-master\YPF Manager\bin\Debug>-p bn.ypf
'-p' is not recognized as an internal or external command,
operable program or batch file.

E:\YPF_Manager_Tool-master\YPF Manager\bin\Debug>-p
'-p' is not recognized as an internal or external command,
operable program or batch file.
_____________

**Comment by Cosetto** [comment]
bruh you have to call the exe name first: **ypf_manager.exe -p bn.ypf**

**Comment by bregassa** [comment]
> bruh you have to call the exe name first: **ypf_manager.exe -p bn.ypf**

LOOLL,, sorry, I don't have any programming background so sometimes I might look stupid haha..
daaamnn it wooorkkk... woo.. I love you man.. I will kiss if you're in front of me right now
