### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by Protey** [arcusmaximus/VNTranslationTools#91]
Where do I read the instructions for this tool so that even a schoolboy can understand it 1...2....3....?
Preferably with examples.

**Comment by Cosetto** [comment]
As said in description, you must prompt vntextpatch.exe with cmd and cmd's path must be in same folder with vntextpatch.exe
Example:
Extract script: vntextpatch.exe extractlocal input_folder script.xlsx
Insert script: vntextpatch.exe insertlocal input_folder script.xlsx output_folder

**Comment by Protey** [comment]
> As said in description, but here's how to use: you must prompt vntextpatch.exe with cmd and cmd's path must be in same folder with vntextpatch.exe Example: Extract script: vntextpatch.exe extractlocal input_folder script.xlsx Insert script: vntextpatch.exe insertlocal input_folder script.xlsx output_folder
Before using VNTextPatch and VNTextProxy, should the VNTextPatch and VNTextProxy folders with their contents be moved to the game directory?
I just can't figure out how to apply VNTextPatch and VNTextProxy to the game, I need a step by step instruction for that.

**Comment by Cosetto** [comment]
Well, take the output scripts from output folder. You SHOULD know how to apply the script back to the game because vntextpatch is for script only. Vntextproxy is for hooking font and display non , throw it and ext_sjis.bin(if have)to same folder with Game.exe, most games uses d3d9.dll

**Comment by PoisonPyte** [comment]
@Protey I can teach you step-by-step how to use VNTextPatch if you're still unsure (including the command prompts thing and possibly text extraction). Send me a message on Discord at PoisonPyte#1449.

**Comment by KuronekoRM** [comment]
@PoisonPyte Hi! Could I send you a message on discord too? I know how to use VNTexTPatch but I don't understand how to use VNTextProxy.

**Comment by Cosetto** [comment]
> @PoisonPyte Hi! Could I send you a message on discord too? I know how to use VNTexTPatch but I don't understand how to use VNTextProxy.

You don't need Vntextproxy unless you need to change font or display non English letters

**Comment by KuronekoRM** [comment]
@Cosetto I translate otome games to spanish, so I need to display stuff like ñ, ¡,  ¿, á, í, ú, é, ó

**Comment by Cosetto** [comment]
> @Cosetto I translate otome games to spanish, so I need to display stuff like ñ, ¡, ¿, á, í, ú, é, ó

If that's the case. You just type those letters in the script normally, insert the scripts, when taking output scripts you will see a file called ext_sjis.bin. Throw ext_sjis.bin, a font(.ttf/.otd) supports Spanish and one of the proxies(most games use d3d9.dll) to same folder with Game.exe

**Comment by KuronekoRM** [comment]
@Cosetto that usually works but I'm having problems with a specific game. I don't want to change the focus of this thread too much so I won't go on about it, but here's my discord if someone wants to help: SolangeSC#5533

**Comment by Cosetto** [comment]
> @Cosetto that usually works but I'm having problems with a specific game. I don't want to change the focus of this thread too much so I won't go on about it, but here's my discord if someone wants to help: SolangeSC#5533

Tell me the game name
