### ISSUE TITLE
Error when switching to full-screen with Qlie engine when using the proxy

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#94]
This is [the game](https://vndb.org/v14240) I tried with, also same result with other proxies
![image](https://user-images.githubusercontent.com/81801486/208088681-2d82b32f-2604-454b-affd-ca1b84123553.png)

I can't tell if this error only occurs with older qlie version (FilePack3.0). There's no error when I tested with newer qlie version(FilePack3.1)

**Comment by Cosetto** [comment]
Fixed, I was using the oldest version of vntextproxy :))
I'll leave the issue here if you need to update
[VNTextProxy.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10308135/VNTextProxy.zip)

**Comment by arcusmaximus** [comment]
If it works with the current version, there's nothing else to update I think.
