### ISSUE TITLE
I'm having some problems from SystemNNN(maybe it not?)

### ISSUE THREAD

**Issue by LittleFIve233** [arcusmaximus/VNTranslationTools#96]
![image](https://user-images.githubusercontent.com/68946023/208378523-5ab1c64a-8818-43a1-8f24-3a34ecf31518.png)
I tried to extract text with the file, but it says "Invalid .spt header".
Here are files

[text.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10257415/text.zip)

Is it my problem or is it not SystemNNN?

**Comment by Cosetto** [comment]
it is not

**Comment by Cosetto** [comment]
Maybe the engine your referring to is GSP, it also uses .spt as script

**Comment by LittleFIve233** [comment]
> Maybe the engine your referring to is GSP, it also uses .spt as script

Okay, thank you very much, I'll google it
