### ISSUE TITLE
Support for Artemis engine .ast

### ISSUE THREAD

**Issue by RedEye13** [arcusmaximus/VNTranslationTools#99]
Hi this is just a little hope I have if anybody here would add support for the .ast file of the Artemis engine the games I've looked in so far all have the files unencrypted so it's just a matter of targeting the text 

![image](https://user-images.githubusercontent.com/30023402/209888488-d9f7d8a1-9064-440b-8a4a-d8e347d63dde.png)
I mean this is editable sure but you know.....It's not ideal

**Comment by Cosetto** [comment]
Well, if you know how to run .lua then here [the tool](https://github.com/regomne/chinesize/tree/master/Artemis/extast) :)) or you can use [this](https://github.com/marcussacana/SacanaWrapper)

**Comment by arcusmaximus** [comment]
Support added.

**Comment by RedEye13** [comment]
Thanks dude works great 

![image](https://user-images.githubusercontent.com/30023402/209995571-160f6f3f-6a2f-4d7b-8b0d-56d138629489.png)
![image](https://user-images.githubusercontent.com/30023402/209995591-812fcb43-348b-4d9a-8d68-fc5662011d45.png)
